#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MPLIS;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/TTBienDong/_BienDong_DSGCN.cshtml")]
    public partial class _Views_TTBienDong__BienDong_DSGCN_cshtml : System.Web.Mvc.WebViewPage<MPLIS.Libraries.Data.XuLyHoSo.Models.DSGCNBDVM>
    {
        public _Views_TTBienDong__BienDong_DSGCN_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<form");

WriteLiteral(" id=\"IDformBienDong_DSGCN\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 4 "..\..\Views\TTBienDong\_BienDong_DSGCN.cshtml"
   Write(Html.HiddenFor(model => model.JSONCha));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <input");

WriteLiteral(" id=\"CurGCNRaID\"");

WriteLiteral(" name=\"CurGCNRaID\"");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" value=\"\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"divBienDongID_DSGCNVAO\"");

WriteLiteral(">\r\n");

            
            #line 7 "..\..\Views\TTBienDong\_BienDong_DSGCN.cshtml"
            
            
            #line default
            #line hidden
            
            #line 7 "..\..\Views\TTBienDong\_BienDong_DSGCN.cshtml"
              Html.RenderPartial("_BienDong_DSGCNVAO");
            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" id=\"divBienDongID_DSGCNRA\"");

WriteLiteral(">\r\n");

            
            #line 10 "..\..\Views\TTBienDong\_BienDong_DSGCN.cshtml"
            
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\TTBienDong\_BienDong_DSGCN.cshtml"
              Html.RenderPartial("_BienDong_DSGCNRA");
            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n</form>\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    $(function () {\r\n        addRowHandlersGCNRA(\"table_DSGCNRAID\");\r\n        " +
"//addRowHandlers(\"table_DSGCNVAOID\");\r\n        $(\'#table_DSGCNRAID tbody\').on(\'c" +
"lick\', \'tr\', function (e) {\r\n            $(this).addClass(\'activerow\').siblings(" +
").removeClass(\'activerow\');\r\n            console.log(\'Click tr!\');\r\n        });\r" +
"\n        function addRowHandlersGCNRA(tableid) {\r\n            var table = docume" +
"nt.getElementById(tableid);\r\n            var rows = table.getElementsByTagName(\"" +
"tr\");\r\n            for (i = 0; i < rows.length; i++) {\r\n                var curr" +
"entRow = rows[i];\r\n                var createClickHandler =\r\n                   " +
" function (row) {\r\n                        return function () {\r\n               " +
"             var id = $(row).attr(\"data-id\");//cell.innerHTML;\r\n                " +
"            document.getElementById(\"CurGCNRaID\").value = id;\r\n                 " +
"           CheckRow(id);\r\n                        };\r\n                    };\r\n  " +
"              currentRow.onclick = createClickHandler(currentRow);\r\n            " +
"}\r\n        }\r\n        function CheckRow(GCNID) {\r\n            var data = documen" +
"t.getElementById(\"JSONCha\").value;\r\n            console.log(\"json value:\" + data" +
");\r\n            var obj = JSON.parse(data);\r\n            console.log(\"json array" +
":\" + obj[GCNID]);\r\n            var arr = obj[GCNID];\r\n            $(\"#table_DSGC" +
"NVAOID input\").each(function () {\r\n                var checked = false;\r\n       " +
"         var id = this.id;\r\n                console.log(\"id row:\" + id);\r\n      " +
"          for (i = 0; i < arr.length; i++)\r\n                    if (id == arr[i]" +
") {\r\n                        console.log(\"Trùng id:\" + id);\r\n                   " +
"     $(this).prop(\"checked\", true);\r\n                        checked = true;\r\n  " +
"                  }\r\n                if (!checked) $(this).prop(\"checked\", false" +
");\r\n            });\r\n        }\r\n    });\r\n\r\n    function Load_TTRIENG_THECHAP_CTQ" +
"UYEN() {\r\n        if ($(\'#divBienDongID_TTRIENG_THECHAP_CTQUYEN\').length) {\r\n   " +
"         console.log(\'Tồn tại divBienDongID_TTRIENG_THECHAP_CTQUYEN!\');\r\n       " +
"     $(\'#divBienDongID_TTRIENG_THECHAP_CTQUYEN\').load(\"/TTBienDong/_BienDong_TTR" +
"IENG_THECHAP_TTQUYEN\", function (responseTxt, statusTxt, xhr) {\r\n               " +
" console.log(\'Load_TTRIENG_THECHAP_CTQUYEN thành công!\');\r\n            });\r\n    " +
"    }\r\n    }\r\n</script>");

        }
    }
}
#pragma warning restore 1591
