#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MPLIS;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/TTBienDong/_Popup_DSTHUAXL.cshtml")]
    public partial class _Views_TTBienDong__Popup_DSTHUAXL_cshtml : System.Web.Mvc.WebViewPage<MPLIS.Libraries.Data.XuLyHoSo.Models.DSThuaDonVM>
    {
        public _Views_TTBienDong__Popup_DSTHUAXL_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\TTBienDong\_Popup_DSTHUAXL.cshtml"
 using (Ajax.BeginForm("Add_DSTHUAXL_RTABLE", "TTBienDong", new AjaxOptions
{
    OnSuccess = "alert('Thêm thửa xử lý thành công')",
    HttpMethod = "Post",
    UpdateTargetId = "divBienDongID_DSTHUA",
    InsertionMode = InsertionMode.Replace
}))
{

            
            #line default
            #line hidden
WriteLiteral("    <table");

WriteLiteral(" class=\"bordered\"");

WriteLiteral(" id=\"popuptable_DSTHUAXLID\"");

WriteLiteral(" data-toggle=\"table\"");

WriteLiteral(">\r\n        <thead>\r\n            <tr>\r\n                <th");

WriteLiteral(" class=\"t50\"");

WriteLiteral(">STT</th>\r\n                <th");

WriteLiteral(" class=\"t150\"");

WriteLiteral(">Xã/phường</th>\r\n                <th");

WriteLiteral(" class=\"t100\"");

WriteLiteral(">SH tờ bản đồ</th>\r\n                <th");

WriteLiteral(" class=\"t100\"");

WriteLiteral(">STT thửa</th>\r\n                <th");

WriteLiteral(" class=\"t100\"");

WriteLiteral(">DT pháp lý (m2)</th>\r\n                <th>Địa chỉ</th>\r\n                <th");

WriteLiteral(" class=\"t100\"");

WriteLiteral(">Hành động</th>\r\n            </tr>\r\n        </thead>\r\n");

            
            #line 23 "..\..\Views\TTBienDong\_Popup_DSTHUAXL.cshtml"
        
            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\TTBienDong\_Popup_DSTHUAXL.cshtml"
          int rTHUAmoiXL = 0;
            if (Model.DSDangKyThua != null)
            {
                foreach (var item in Model.DSDangKyThua)
                {
                    rTHUAmoiXL = rTHUAmoiXL + 1;

            
            #line default
            #line hidden
WriteLiteral("                    <tr");

WriteLiteral(" data-id=\"");

            
            #line 29 "..\..\Views\TTBienDong\_Popup_DSTHUAXL.cshtml"
                            Write(item.THUADATID);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                        <td>\r\n");

WriteLiteral("                            ");

            
            #line 31 "..\..\Views\TTBienDong\_Popup_DSTHUAXL.cshtml"
                       Write(rTHUAmoiXL);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                        <td>\r\n");

WriteLiteral("                            ");

            
            #line 34 "..\..\Views\TTBienDong\_Popup_DSTHUAXL.cshtml"
                       Write(item.XaPhuong);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                        <td>\r\n");

WriteLiteral("                            ");

            
            #line 37 "..\..\Views\TTBienDong\_Popup_DSTHUAXL.cshtml"
                       Write(item.SHToBanDo);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                        <td>\r\n");

WriteLiteral("                            ");

            
            #line 40 "..\..\Views\TTBienDong\_Popup_DSTHUAXL.cshtml"
                       Write(item.STTThua);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                        <td>\r\n");

WriteLiteral("                            ");

            
            #line 43 "..\..\Views\TTBienDong\_Popup_DSTHUAXL.cshtml"
                       Write(item.DienTich);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                        <td>\r\n");

WriteLiteral("                            ");

            
            #line 46 "..\..\Views\TTBienDong\_Popup_DSTHUAXL.cshtml"
                       Write(item.DiaChi);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                        <td>\r\n                  " +
"          <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"DSTHUAXL_CHON\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1792), Tuple.Create("\"", 1815)
            
            #line 49 "..\..\Views\TTBienDong\_Popup_DSTHUAXL.cshtml"
, Tuple.Create(Tuple.Create("", 1800), Tuple.Create<System.Object, System.Int32>(item.THUADATID
            
            #line default
            #line hidden
, 1800), false)
);

WriteLiteral(" />\r\n                        </td>\r\n                    </tr>\r\n");

            
            #line 52 "..\..\Views\TTBienDong\_Popup_DSTHUAXL.cshtml"
                }
            }
        
            
            #line default
            #line hidden
WriteLiteral("\r\n    </table>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"clear\"");

WriteLiteral("></div>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"collbutton-xs-12\"");

WriteLiteral(">\r\n        <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"checkall_DSTHUAXL_CHON\"");

WriteLiteral(" /><span>Check All</span>\r\n        <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Lưu\"");

WriteLiteral(" class=\"btn\"");

WriteLiteral(" />\r\n    </div>\r\n");

            
            #line 61 "..\..\Views\TTBienDong\_Popup_DSTHUAXL.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    function toggleCheckeddsTHUAXL(statusDSTHUAXL_CHON) {
        $(""#popuptable_DSTHUAXLID input"").each(function () {
            $(this).prop(""checked"", statusDSTHUAXL_CHON);
        });
    }
    $(document).ready(function () {
        $(""#checkall_DSTHUAXL_CHON"").prop(""checked"", false);
        $(""#checkall_DSTHUAXL_CHON"").click(function () {
            var statusDSTHUAXL_CHON = $(""#checkall_DSTHUAXL_CHON"").prop(""checked"");
            toggleCheckeddsTHUAXL(statusDSTHUAXL_CHON);
        });
    });
</script>");

        }
    }
}
#pragma warning restore 1591
