#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MPLIS;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/XLHSGiayChungNhan/GiayChungNhan_Main.cshtml")]
    public partial class _Views_XLHSGiayChungNhan_GiayChungNhan_Main_cshtml : System.Web.Mvc.WebViewPage<MPLIS.Libraries.Data.XuLyHoSo.Models.GiayChungNhanLS>
    {
        public _Views_XLHSGiayChungNhan_GiayChungNhan_Main_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\XLHSGiayChungNhan\GiayChungNhan_Main.cshtml"
  
    bool EnableLoad = false;
    if (Model.TRANGTHAIXULY == "Y" || (Model.TRANGTHAIXULY == "S" && Model.NGUOIID != null && Model.NGUOIID != ""))
    {
        EnableLoad = true;
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" id=\"divGiayChungNhanID\"");

WriteLiteral(">\r\n    ");

WriteLiteral("\r\n    <div");

WriteLiteral(" id=\"tabGCN_TTChung_ID\"");

WriteLiteral(" class=\"row panel\"");

WriteLiteral(" style=\"margin-bottom: 5px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"btn btn-default btn-block tab-doc\"");

WriteLiteral(" style=\"text-align:left;\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" style=\"color: blue;font-weight: bold;\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-parent=\"#divGiayChungNhanID\"");

WriteLiteral(" href=\"#collapse_GCN_TTChung\"");

WriteLiteral(">\r\n                Thông tin chung giấy chứng nhận\r\n            </a>\r\n        </d" +
"iv>\r\n        <div");

WriteLiteral(" id=\"collapse_GCN_TTChung\"");

WriteLiteral(" class=\"panel-collapse collapse in\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"divGCN_TTChung_ID\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 21 "..\..\Views\XLHSGiayChungNhan\GiayChungNhan_Main.cshtml"
           Write(Html.Partial("GiayChungNhan_Main_TTChung"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n    ");

WriteLiteral("\r\n");

            
            #line 26 "..\..\Views\XLHSGiayChungNhan\GiayChungNhan_Main.cshtml"
    
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\XLHSGiayChungNhan\GiayChungNhan_Main.cshtml"
     if (EnableLoad)
    {
        if (Model.DSTyLeSoHuu != null && Model.DSTyLeSoHuu.Count > 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" id=\"divTabGCNTLSHID\"");

WriteLiteral(" class=\"row panel\"");

WriteLiteral(" style=\"margin-bottom: 5px;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"btn btn-default btn-block tab-doc\"");

WriteLiteral(" style=\"text-align:left;\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" style=\"color: blue;font-weight: bold;\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-parent=\"#divGiayChungNhanID\"");

WriteLiteral(" href=\"#collapse_GCN_TLSH\"");

WriteLiteral(">\r\n                        Danh sách tỷ lệ sở hữu\r\n                    </a>\r\n    " +
"            </div>\r\n                <div");

WriteLiteral(" id=\"collapse_GCN_TLSH\"");

WriteLiteral(" class=\"panel-collapse collapse\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" id=\"divGCN_TLSH_ID\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 38 "..\..\Views\XLHSGiayChungNhan\GiayChungNhan_Main.cshtml"
                   Write(Html.Partial("GiayChungNhan_Main_TLSH"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n");

            
            #line 42 "..\..\Views\XLHSGiayChungNhan\GiayChungNhan_Main.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"row panel\"");

WriteLiteral(" style=\"margin-bottom: 5px;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"btn btn-default btn-block tab-doc\"");

WriteLiteral(" style=\"text-align:left;\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" style=\"color: blue;font-weight: bold;\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-parent=\"#divGiayChungNhanID\"");

WriteLiteral(" href=\"#collapse_GCN_HanChe\"");

WriteLiteral(">\r\n                    Danh sách hạn chế\r\n                </a>\r\n            </div" +
">\r\n            <div");

WriteLiteral(" id=\"collapse_GCN_HanChe\"");

WriteLiteral(" class=\"panel-collapse collapse\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" id=\"divGCN_Main_HanChe\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 51 "..\..\Views\XLHSGiayChungNhan\GiayChungNhan_Main.cshtml"
               Write(Html.Partial("GiayChungNhan_Main_HanChe"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row panel\"");

WriteLiteral(" style=\"margin-bottom: 5px;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"btn btn-default btn-block tab-doc\"");

WriteLiteral(" style=\"text-align:left;\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" style=\"color: blue;font-weight: bold;\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-parent=\"#divGiayChungNhanID\"");

WriteLiteral(" href=\"#collapse_GCN_SDDAT\"");

WriteLiteral(">\r\n                    Danh sách quyền sử dụng đất\r\n                </a>\r\n       " +
"     </div>\r\n            <div");

WriteLiteral(" id=\"collapse_GCN_SDDAT\"");

WriteLiteral(" class=\"panel-collapse collapse\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" id=\"divGCN_Main_SDDATID\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 63 "..\..\Views\XLHSGiayChungNhan\GiayChungNhan_Main.cshtml"
               Write(Html.Partial("GiayChungNhan_Main_SDDat"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row panel\"");

WriteLiteral(" style=\"margin-bottom: 5px;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"btn btn-default btn-block tab-doc\"");

WriteLiteral(" style=\"text-align:left;\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" style=\"color: blue;font-weight: bold;\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-parent=\"#divGiayChungNhanID\"");

WriteLiteral(" href=\"#collapse_GCN_SHTS\"");

WriteLiteral(">\r\n                    Danh sách quyền sở hữu tài sản\r\n                </a>\r\n    " +
"        </div>\r\n            <div");

WriteLiteral(" id=\"collapse_GCN_SHTS\"");

WriteLiteral(" class=\"panel-collapse collapse\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" id=\"divGCN_Main_SHTaiSanID\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 75 "..\..\Views\XLHSGiayChungNhan\GiayChungNhan_Main.cshtml"
               Write(Html.Partial("GiayChungNhan_Main_SHTaiSan"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row panel\"");

WriteLiteral(" style=\"margin-bottom: 5px;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"btn btn-default btn-block tab-doc\"");

WriteLiteral(" style=\"text-align:left;\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" style=\"color: blue;font-weight: bold;\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-parent=\"#divGiayChungNhanID\"");

WriteLiteral(" href=\"#collapse_GCN_QLD\"");

WriteLiteral(">\r\n                    Danh sách quyền quản lý đất\r\n                </a>\r\n       " +
"     </div>\r\n            <div");

WriteLiteral(" id=\"collapse_GCN_QLD\"");

WriteLiteral(" class=\"panel-collapse collapse\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" id=\"divGCN_Main_QLDATID\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 87 "..\..\Views\XLHSGiayChungNhan\GiayChungNhan_Main.cshtml"
               Write(Html.Partial("GiayChungNhan_Main_QLDat"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row panel\"");

WriteLiteral(" style=\"margin-bottom: 5px;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"btn btn-default btn-block tab-doc\"");

WriteLiteral(" style=\"text-align:left;\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" style=\"color: blue;font-weight: bold;\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-parent=\"#divGiayChungNhanID\"");

WriteLiteral(" href=\"#collapse_GCN_BIENDONG\"");

WriteLiteral(">\r\n                    Danh sách biến động\r\n                </a>\r\n            </d" +
"iv>\r\n            <div");

WriteLiteral(" id=\"collapse_GCN_BIENDONG\"");

WriteLiteral(" class=\"panel-collapse collapse\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" id=\"divGCN_Main_BIENDONGID\"");

WriteLiteral(">\r\n                </div>\r\n            </div>\r\n        </div>\r\n");

            
            #line 102 "..\..\Views\XLHSGiayChungNhan\GiayChungNhan_Main.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    $(document).ready(function () {\r\n        trigger_tab_doc();\r\n    })\r\n</scr" +
"ipt>");

        }
    }
}
#pragma warning restore 1591
