#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MPLIS;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/XLHSGiayChungNhan/Popup_DSThua.cshtml")]
    public partial class _Views_XLHSGiayChungNhan_Popup_DSThua_cshtml : System.Web.Mvc.WebViewPage<MPLIS.Libraries.Data.XuLyHoSo.Models.DSThuaDatVM>
    {
        public _Views_XLHSGiayChungNhan_Popup_DSThua_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\'modal fade\'");

WriteLiteral(" id=\'modalformDSThua\'");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\'modal-dialog modal-lg\'");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\'modal-content\'");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\'modal-header\'");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\'button\'");

WriteLiteral(" class=\'close\'");

WriteLiteral(" data-dismiss=\'modal\'");

WriteLiteral(">&times;</button>\r\n                <h4");

WriteLiteral(" class=\'modal-title\'");

WriteLiteral(">");

            
            #line 8 "..\..\Views\XLHSGiayChungNhan\Popup_DSThua.cshtml"
                                   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\'modal-body p-0\'");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" class=\"nav nav-tabs nav-justified\"");

WriteLiteral(">\r\n                    <li");

WriteLiteral(" class=\"active\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" id=\"Popup_DSThua_OpenTab1ID\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(" href=\"#gcn-popup-qd-tab01ID\"");

WriteLiteral(">Thêm quyền theo thửa đất</a>\r\n                    </li>\r\n                    <li" +
">\r\n                        <a");

WriteLiteral(" id=\"Popup_DSThua_OpenTab2ID\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(" href=\"#gcn-popup-qd-tab02ID\"");

WriteLiteral(">Thêm quyền theo mục đích sử dụng</a>\r\n                    </li>\r\n               " +
" </ul>\r\n                <div");

WriteLiteral(" class=\"tab-content p-10\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" id=\"gcn-popup-qd-tab01ID\"");

WriteLiteral(" class=\"tab-pane fade in active\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 21 "..\..\Views\XLHSGiayChungNhan\Popup_DSThua.cshtml"
                   Write(Html.Partial("DSThuaTheoThuaID"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" id=\"gcn-popup-qd-tab02ID\"");

WriteLiteral(" class=\"tab-pane fade\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 24 "..\..\Views\XLHSGiayChungNhan\Popup_DSThua.cshtml"
                   Write(Html.Partial("DSThuaTheoMDSDID"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n       " +
" </div>\r\n    </div>\r\n</div>\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    $(document).ready(function () {\r\n    })\r\n</script>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
