#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
    using AppCore.Models;
    
    #line default
    #line hidden
    using MPLIS;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/XLHSDangKy/_DonDangKy_CanHo.cshtml")]
    public partial class _Views_XLHSDangKy__DonDangKy_CanHo_cshtml : System.Web.Mvc.WebViewPage<AppCore.Models.DangKyTaiSan>
    {
        public _Views_XLHSDangKy__DonDangKy_CanHo_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
  using (Html.BeginForm("_DonDangKy_TSNHARIENGLE", "XLHSDangKy", FormMethod.Post, new { @id = "ThemMoiCanHo" }))
    {
        
            
            #line default
            #line hidden
            
            #line 5 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 5 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
                                
        
            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
   Write(Html.HiddenFor(m => m.CurCanHo.CANHOID, new { @class = "form-control" }));

            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
                                                                                 
        
            
            #line default
            #line hidden
            
            #line 7 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
   Write(Html.HiddenFor(m => m.CurCanHo.uId, new { @class = "form-control" }));

            
            #line default
            #line hidden
            
            #line 7 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
                                                                             


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 12 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.LabelFor(Model=>Model.CurNhaChungCu.KHUCHUNGCUID,"Khu chung cư", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-7\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 15 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.DropDownListFor(m => m.CurNhaChungCu.KHUCHUNGCUID, new SelectList(ViewBag.listkhuchungcu, "KHUCHUNGCUID", "TENKHU"), "---- Lựa chọn ----", new { @class = "form-control input-sm", @id = "drpkhuchungcu" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btnthemkhuchungcu\"");

WriteLiteral(" value=\"Thêm mới\"");

WriteLiteral(" />\r\n                </div>\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 25 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.LabelFor(Model=>Model.CurCanHo.NHACHUNGCUID,"Nhà chung cư", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-7\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 28 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.DropDownListFor(m => m.CurCanHo.NHACHUNGCUID, new SelectList(ViewBag.listnhachungcu, "NHACHUNGCUID", "TENCHUNGCU"), "---- Lựa chọn ----", new { @class = "form-control input-sm", @id = "drpnhachungcu" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btnthemnhachungcuch\"");

WriteLiteral(" value=\"Thêm mới\"");

WriteLiteral(" />\r\n                </div>\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 38 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.LabelFor(Model => Model.CurCanHo.SOHIEUCANHO, "Số hiệu căn hộ", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 41 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.TextBoxFor(m => m.CurCanHo.SOHIEUCANHO, new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div>\r\n                " +
"<div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 46 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.LabelFor(Model=>Model.CurCanHo.DIENTICHSAN,"Diện tích sàn", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 49 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.TextBoxFor(m => m.CurCanHo.DIENTICHSAN, new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 56 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.LabelFor(Model=>Model.CurCanHo.HINHTHUCSOHUU,"Hình thức sở hữu", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 59 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.TextBoxFor(m => m.CurCanHo.HINHTHUCSOHUU, new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div>\r\n                " +
"<div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 64 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.LabelFor(Model=>Model.CurCanHo.TANGSO,"Tầng số", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 67 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.TextBoxFor(m => m.CurCanHo.TANGSO, new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 74 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.LabelFor(Model=>Model.CurCanHo.THOIHANSOHUU,"Thời hạn sở hữu", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 77 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.TextBoxFor(m => m.CurCanHo.THOIHANSOHUU, new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div>\r\n                " +
"<div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 82 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.LabelFor(Model=>Model.CurCanHo.TINHTRANGDANGKY,"Tình trạng đăng ký", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 85 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.DropDownListFor(m => m.CurCanHo.TINHTRANGDANGKY, new SelectList(ViewBag.lsttinhtrangdk, "MALOAITRANGTHAIDANGKYCAPGCN", "TENLOAITRANGTHAIDANGKYCAPGCN"), new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 92 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.LabelFor(Model => Model.CurCanHo.NGUONGOC, "Nguồn gốc", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 95 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.TextBoxFor(m => m.CurCanHo.NGUONGOC, new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div>\r\n                " +
"<div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 100 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.LabelFor(Model => Model.CurCanHo.NAMHOANCONG, "Năm hoàn công", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 103 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.TextBoxFor(m => m.CurCanHo.NAMHOANCONG, new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 111 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.LabelFor(Model => Model.CurCanHo.DTSH_RIENG, "Diện tích sở hữu riêng", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral("style=\"padding-top: 11px;\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 114 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.TextBoxFor(m => m.CurCanHo.DTSH_RIENG, new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div>\r\n                " +
"<div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 119 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.LabelFor(Model => Model.CurCanHo.DTSH_CHUNG_CDT, "Diện tích sở hữu chung chủ đầu tư", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(" style=\"padding-top: 11px;\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 122 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.TextBoxFor(m => m.CurCanHo.DTSH_CHUNG_CDT, new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 130 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.LabelFor(Model => Model.CurCanHo.DT_PT_KHONGRIENGLE, "Diện tích phát triển không riêng lẻ", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral("style=\"padding-top: 11px;\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 133 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.TextBoxFor(m => m.CurCanHo.DT_PT_KHONGRIENGLE, new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div>\r\n                " +
"<div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 138 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.LabelFor(Model => Model.CurCanHo.DTSH_CHUNG_NSDD, "Diện tích sở hữu chung người sử dụng", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(" style=\"padding-top: 11px;\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 141 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.TextBoxFor(m => m.CurCanHo.DTSH_CHUNG_NSDD, new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 148 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.LabelFor(Model => Model.CurCanHo.DT_PT_RIENGLE, "diện tích phát triển riêng lẻ", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral("style=\"padding-top: 11px;\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 151 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.TextBoxFor(m => m.CurCanHo.DT_PT_RIENGLE, new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div>\r\n                " +
"<div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 156 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.LabelFor(Model => Model.CurCanHo.DT_HT_NVTC, "Diện tích hoàn thành nghĩa vụ tài chính", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral("style=\"padding-top: 11px;\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 159 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.TextBoxFor(m => m.CurCanHo.DT_HT_NVTC, new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 166 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.LabelFor(Model => Model.CurCanHo._CO_HSXN_NHADUYNHAT, "Có hồ sơ xác nhận nhà duy nhất", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral("style=\"padding-top: 13px;\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 169 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
               Write(Html.CheckBoxFor(m => m.CurCanHo._CO_HSXN_NHADUYNHAT));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n");

            
            #line 173 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"clear\"");

WriteLiteral("></div>\r\n");

            
            #line 175 "..\..\Views\XLHSDangKy\_DonDangKy_CanHo.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n<script>\r\n    $(function () {\r\n        $(\'#drpnhachungcu\').change(function () {" +
"\r\n            if ($(\'#drpnhachungcu\').val() != null) {\r\n                document" +
".getElementById(\"btnthemnhachungcuch\").value = \"\"+\"  Sửa  \"+\"\";\r\n            }\r\n" +
"            else {\r\n                document.getElementById(\"btnthemnhachungcuch" +
"\").value = \"Thêm mới\";\r\n            }\r\n        });\r\n        $(\'#drpkhuchungcu\')." +
"change(function () {\r\n            if ($(\'#drpkhuchungcu\').val() != null) {\r\n    " +
"            document.getElementById(\"btnthemkhuchungcu\").value =\"\"+ \"  Sửa  \"+\"\"" +
";\r\n            }\r\n            else {\r\n                document.getElementById(\"b" +
"tnthemkhuchungcu\").value = \"Thêm mới\";\r\n            }\r\n        });\r\n        $(\"#" +
"btnthemkhuchungcu\").on(\"click\", function () {\r\n            var drpkhuchungcu = d" +
"ocument.getElementById(\'drpkhuchungcu\');\r\n            if ($(\'#drpkhuchungcu\').va" +
"l() != \"\") {\r\n                var r = drpkhuchungcu.options[drpkhuchungcu.select" +
"edIndex].innerHTML;\r\n                console.log(\'text\' + r);\r\n                v" +
"ar t = $(\'#drpkhuchungcu\').val();\r\n                console.log(\'id\' + t);\r\n     " +
"       }\r\n            else {\r\n                var r = \"\";\r\n                var t" +
" = \"\";\r\n            }\r\n            console.log(\"click button\");\r\n            $.a" +
"jax({\r\n                type: \"GET\",\r\n                url: \"/XLHSDangKy/_DonDangK" +
"y_KhuChungCu\",\r\n                data: { id: $(\'#drpkhuchungcu\').val().trim()},\r\n" +
"                success: function (html) {\r\n\r\n                    $(\'#dialogform" +
"KHUCHUNGCU\').html(html);\r\n                    var options = {\r\n                 " +
"       \"backdrop\": \"static\",\r\n                        \"show\": true\r\n            " +
"        }\r\n                    $(\"#modalformKhuChungCu\").modal(options);\r\n      " +
"              \r\n                    if (t != null || t != \"\") {\r\n               " +
"         console.log(document.getElementById(\"title_popup_kcc\").innerHTML);\r\n   " +
"                     document.getElementById(\"title_popup_kcc\").innerHTML =\"Khu " +
"chung cư \"+ r.trim();\r\n                        document.getElementById(\"CurKCCID" +
"\").value = t.trim();\r\n                        console.log(\"CurKCCID: \" + documen" +
"t.getElementById(\"CurKCCID\").value);\r\n                    }\r\n                }\r\n" +
"            });\r\n        });\r\n        $(\"#btnthemnhachungcuch\").on(\"click\", func" +
"tion () {\r\n            var drpnhachungcu = document.getElementById(\'drpnhachungc" +
"u\');\r\n            if ($(\'#drpnhachungcu\').val() != \"\") {\r\n                var r " +
"= drpnhachungcu.options[drpnhachungcu.selectedIndex].innerHTML;\r\n               " +
" console.log(\'text\' + r);\r\n                var t = $(\'#drpkhuchungcu\').val();\r\n " +
"               console.log(\'id\' + t);\r\n            }\r\n            else {\r\n      " +
"          var r = \"\";\r\n                var t = \"\";\r\n            }\r\n         var " +
" a= $(\'#drpnhachungcu\').val();\r\n            console.log(\"dropnha chung cu\"+a);\r\n" +
"            console.log(\"click button\");\r\n            $.ajax({\r\n                " +
"type: \"GET\",\r\n                url: \"/XLHSDangKy/_Popup_NhaChungCu\",\r\n           " +
"     data: { a: $(\'#drpnhachungcu\').val().trim() },\r\n                success: fu" +
"nction (response, startus, xhr) {\r\n                    $(\'#dialogformNHACHUNGCU\'" +
").html(response);\r\n                    var options = {\r\n                        " +
"\"backdrop\": \"static\",\r\n                        \"show\": true\r\n                   " +
" }\r\n                    $(\"#modalformNhaChungCu\").modal(options);\r\n             " +
"       if (t != null || t != \"\") {\r\n                        console.log(document" +
".getElementById(\"title_popup_ncc\").innerHTML);\r\n                        document" +
".getElementById(\"title_popup_ncc\").innerHTML = \"Nhà chung cư \" + r.trim();\r\n    " +
"                }\r\n                    if ($(\'#drpkhuchungcunccCH\').val() != nul" +
"l && $(\'#drpkhuchungcunccCH\').val() != \"\") {\r\n                        document.g" +
"etElementById(\"btnthemkhuchungcunccCH\").value = \"\" + \"  Sửa  \" + \"\";\r\n          " +
"          }\r\n                    else {\r\n                        document.getEle" +
"mentById(\"btnthemkhuchungcunccCH\").value = \"Thêm mới\";\r\n                    }\r\n " +
"                   \r\n                }\r\n            });\r\n        });\r\n\r\n    });\r" +
"\n</script>");

        }
    }
}
#pragma warning restore 1591
