#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\XLHSDangKy\_DonDangKy_DSThua_TTChiTietThua_MDSD.cshtml"
    using AppCore.Models;
    
    #line default
    #line hidden
    using MPLIS;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/XLHSDangKy/_DonDangKy_DSThua_TTChiTietThua_MDSD.cshtml")]
    public partial class _Views_XLHSDangKy__DonDangKy_DSThua_TTChiTietThua_MDSD_cshtml : System.Web.Mvc.WebViewPage<DC_THUADAT>
    {
        public _Views_XLHSDangKy__DonDangKy_DSThua_TTChiTietThua_MDSD_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" id=\"div_MDSD_Thua\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"padding: 0;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"box-header with-border\"");

WriteLiteral(">\r\n                    <h3");

WriteLiteral(" class=\"box-title\"");

WriteLiteral(">Danh sách mục đích sử dụng</h3>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"box-body\"");

WriteLiteral(">\r\n                    <table");

WriteLiteral(" id=\"table_MDSDTHUA\"");

WriteLiteral(" class=\"table table-bordered\"");

WriteLiteral(@">
                        <thead>
                            <tr>
                                <th hidden>ID</th>
                                <th>#</th>
                                <th>MĐSD</th>
                                <th>Diện tích(m<sup>2</sup>)</th>
                                <th>Thời hạn SD</th>
                                <th>Sử dụng chung</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
");

            
            #line 25 "..\..\Views\XLHSDangKy\_DonDangKy_DSThua_TTChiTietThua_MDSD.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\XLHSDangKy\_DonDangKy_DSThua_TTChiTietThua_MDSD.cshtml"
                              
                                int rdsgcntable = 0;
                                if (Model != null)
                                {
                                    if (Model.DSMucDichSuDungDat != null)
                                    {
                                        foreach (var item in Model.DSMucDichSuDungDat)
                                        {
                                            rdsgcntable = rdsgcntable + 1;

            
            #line default
            #line hidden
WriteLiteral("                                            <tr");

WriteLiteral(" data-mucdichsudungdatid=\"");

            
            #line 34 "..\..\Views\XLHSDangKy\_DonDangKy_DSThua_TTChiTietThua_MDSD.cshtml"
                                                                    Write(item.MUCDICHSUDUNGDATID);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                                                <td hidden>");

            
            #line 35 "..\..\Views\XLHSDangKy\_DonDangKy_DSThua_TTChiTietThua_MDSD.cshtml"
                                                      Write(item.MUCDICHSUDUNGDATID);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                    ");

            
            #line 37 "..\..\Views\XLHSDangKy\_DonDangKy_DSThua_TTChiTietThua_MDSD.cshtml"
                                               Write(rdsgcntable);

            
            #line default
            #line hidden
WriteLiteral(".\r\n                                                </td>\r\n                       " +
"                         <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                    ");

            
            #line 40 "..\..\Views\XLHSDangKy\_DonDangKy_DSThua_TTChiTietThua_MDSD.cshtml"
                                               Write(item.TenMDSD);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                </td>\r\n                        " +
"                        <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                    ");

            
            #line 43 "..\..\Views\XLHSDangKy\_DonDangKy_DSThua_TTChiTietThua_MDSD.cshtml"
                                               Write(item.DIENTICH);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                </td>\r\n                        " +
"                        <td>\r\n");

WriteLiteral("                                                    ");

            
            #line 46 "..\..\Views\XLHSDangKy\_DonDangKy_DSThua_TTChiTietThua_MDSD.cshtml"
                                               Write(item.THOIHANSUDUNG);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                </td>\r\n                        " +
"                        <td>\r\n");

WriteLiteral("                                                    ");

            
            #line 49 "..\..\Views\XLHSDangKy\_DonDangKy_DSThua_TTChiTietThua_MDSD.cshtml"
                                               Write(Html.CheckBoxFor(a=>item._SUDUNGCHUNG, new { @disabled = "true" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                </td>\r\n                        " +
"                        <td>\r\n                                                  " +
"  <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-xs btn-heading\"");

WriteLiteral(" value=\"Xóa\"");

WriteLiteral(" onclick=\"xoamdsd(this)\"");

WriteLiteral(" />\r\n                                                    <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-xs btn-heading\"");

WriteLiteral(" value=\"Vị trí\"");

WriteLiteral(" onclick=\"vitrimdsd(this)\"");

WriteLiteral(" />\r\n                                                </td>\r\n                     " +
"                       </tr>\r\n");

            
            #line 56 "..\..\Views\XLHSDangKy\_DonDangKy_DSThua_TTChiTietThua_MDSD.cshtml"
                                        }
                                    }
                                }
                            
            
            #line default
            #line hidden
WriteLiteral("\r\n                        </tbody>\r\n                    </table>\r\n               " +
" </div>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"padding: 0;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"box-header with-border\"");

WriteLiteral(">\r\n                    <h3");

WriteLiteral(" class=\"box-title\"");

WriteLiteral(">Danh sách vị trí trong mục đích sử dụng</h3>\r\n                </div>\r\n          " +
"      <div");

WriteLiteral(" class=\"box-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" id=\"Div_DSViTri\"");

WriteLiteral(">\r\n                    </div>\r\n\r\n                </div>\r\n            </div>\r\n    " +
"    </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"box-header with-border\"");

WriteLiteral(">\r\n                <h3");

WriteLiteral(" class=\"box-title\"");

WriteLiteral(">Thông tin chi tiết mục đích sử dụng</h3>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"box-body\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" id=\"ChiTietMDSD\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 85 "..\..\Views\XLHSDangKy\_DonDangKy_DSThua_TTChiTietThua_MDSD.cshtml"
               Write(Html.Partial("DonDangKy_DSThua_ChiTietMDSD"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r" +
"\n<script>\r\n\r\n    $(document).ready(function () {\r\n        var tableMD= InitDataT" +
"ableXLHS($(\'#table_MDSDTHUA\'));\r\n        tableMD.rows().nodes().on(\"click\", \"tbo" +
"dy tr\", function () {\r\n            console.log(\"CLICK\");\r\n            if (tableM" +
"D.rows().nodes().length > 0) {\r\n                if ($(tableMD.row(this).node())." +
"attr(\'class\').indexOf(\'activerow\') != -1) {\r\n                    $(tableMD.row(t" +
"his).node()).removeClass(\'activerow\');\r\n                } else {\r\n              " +
"      $(tableMD.rows().nodes()).removeClass(\'activerow\');\r\n                    $" +
"(tableMD.row(this).node()).addClass(\'activerow\');\r\n                } var idMDSD " +
"= $(this)[0].cells[0].innerHTML;\r\n                $.ajax({\r\n                    " +
"type: \"POST\",\r\n                    url: \"/XLHSDangKy/ChiTietMDSD\",\r\n            " +
"        data: { idmdsdthuadat: idMDSD.trim() },\r\n                    datatype: \"" +
"html\",\r\n                    success: function (data) {\r\n                        " +
"$(\'#ChiTietMDSD\').html(data);\r\n                        if ($(drpLoaiThoiHan).val" +
"() != 0) {\r\n                            console.log($(\'#TUNGAY\').val());\r\n      " +
"                      $(\'#MDSDTuNgay\').prop(\"disabled\", false);\r\n               " +
"             $(\'#MDSDDenNgay\').prop(\"disabled\", false);\r\n                       " +
" }\r\n                        else {\r\n                            $(\'#MDSDTuNgay\')" +
".prop(\"disabled\", true);\r\n                            $(\'#MDSDDenNgay\').prop(\"di" +
"sabled\", true);\r\n                        }\r\n                    }\r\n             " +
"   })\r\n\r\n                $.ajax({\r\n                    type: \"POST\",\r\n          " +
"          url: \"/XLHSDangKy/DanhSachViTri\",\r\n                    data: { idmdsdt" +
"huadat: idMDSD.trim() },\r\n                    datatype: \"html\",\r\n               " +
"     success: function (data) {\r\n                        $(\'#Div_DSViTri\').html(" +
"data);\r\n\r\n                    }\r\n                })\r\n            }\r\n\r\n        })" +
"\r\n        tableMD.rows().nodes().on(\"click\", \"tbody tr input\", function (event) " +
"{\r\n            event.stopPropagation();\r\n        });\r\n    });\r\n    function xoam" +
"dsd(button) {\r\n        var ans = confirm(\"Bạn chắc chắn muốn xóa?\");\r\n     " +
"   //=== If user pressed Ok then delete the record else do nothing.\r\n        if " +
"(ans == true) {\r\n            var empTab = document.getElementById(\'table_MDSDTHU" +
"A\');\r\n            var index = button.parentNode.parentNode.rowIndex;\r\n          " +
"  var mucdichid = empTab.rows[index].cells[0].innerHTML;\r\n            $.ajax({\r\n" +
"                type: \"POST\",\r\n                url: \"/XLHSDangKy/XoaMDSDThua\",\r\n" +
"                dataType: \"html\",\r\n                data: { mucdichid: mucdichid." +
"trim()},\r\n                success: function (html) {\r\n                    consol" +
"e.log(\"SUCCES\");\r\n                    alert(\"Xóa  thành công!\");\r\n            " +
"        $(\'#div_MDSD_Thua\').html(html);\r\n                },\r\n            });\r\n  " +
"      }\r\n    }\r\n    function vitrimdsd(button) {\r\n        var empTab = document." +
"getElementById(\'table_MDSDTHUA\');\r\n        var index = button.parentNode.parentN" +
"ode.rowIndex;\r\n        var mucdichid = empTab.rows[index].cells[0].innerHTML;\r\n " +
"       $.ajax({\r\n            type: \"POST\",\r\n            url: \"/XLHSDangKy/LoadVi" +
"Tri\",\r\n            dataType: \"html\",\r\n            data: { mucdichid: mucdichid.t" +
"rim() },\r\n            success: function (data) {\r\n                console.log(\"S" +
"UCCES\");\r\n                $(\'#ChiTietMDSD\').html(data);\r\n            },\r\n       " +
" });\r\n    }\r\n</script>");

        }
    }
}
#pragma warning restore 1591
