#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
    using AppCore.Models;
    
    #line default
    #line hidden
    using MPLIS;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/XLHSDangKy/_DonDangKy_HangMucCongTrinh.cshtml")]
    public partial class _Views_XLHSDangKy__DonDangKy_HangMucCongTrinh_cshtml : System.Web.Mvc.WebViewPage<AppCore.Models.DangKyTaiSan>
    {
        public _Views_XLHSDangKy__DonDangKy_HangMucCongTrinh_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
  using (Html.BeginForm("_DonDangKy_TSNHARIENGLE", "XLHSDangKy", FormMethod.Post, new { @id = "ThemMoiHangMucCongTrinh" }))
    {
        
            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
                                
        
            
            #line default
            #line hidden
            
            #line 7 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
   Write(Html.HiddenFor(m => m.CurHangMucCongTrinh.HANGMUCCONGTRINHID, new { @class = "form-control" }));

            
            #line default
            #line hidden
            
            #line 7 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
                                                                                                       
        
            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
   Write(Html.HiddenFor(m => m.CurHangMucCongTrinh.uId, new { @class = "form-control" }));

            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
                                                                                        


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 13 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
               Write(Html.LabelFor(Model => Model.CurHangMucCongTrinh.CONGTRINHXAYDUNGID, "Tên công trình", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 16 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
               Write(Html.DropDownListFor(m => m.CurHangMucCongTrinh.CONGTRINHXAYDUNGID, new SelectList(ViewBag.listcongtrinhxaydung, "CONGTRINHXAYDUNGID", "TENCONGTRINH"), "---- Lựa chọn ----", new { @class = "form-control input-sm", @id = "drpcongtrinhxaydung" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div>\r\n                " +
"<div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 21 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
               Write(Html.LabelFor(Model => Model.tenxats, "Tên xã/phường", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 24 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
               Write(Html.TextBoxFor(m => m.tenxats, new { @class = "form-control input-sm", @readonly = "true" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 32 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
               Write(Html.LabelFor(Model => Model.CurHangMucCongTrinh.TENHANGMUC, "Tên hạng mục", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 35 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
               Write(Html.TextBoxFor(m => m.CurHangMucCongTrinh.TENHANGMUC, new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n\r\n            <div>\r\n              " +
"  <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 41 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
               Write(Html.LabelFor(Model=>Model.CurHangMucCongTrinh.DIENTICHSAN,"Diện tích sàn", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 44 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
               Write(Html.TextBoxFor(m => m.CurHangMucCongTrinh.DIENTICHSAN, new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 52 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
               Write(Html.LabelFor(Model=>Model.CurHangMucCongTrinh.DIENTICHXAYDUNG,"Diện tích xây dựng", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 55 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
               Write(Html.TextBoxFor(m => m.CurHangMucCongTrinh.DIENTICHXAYDUNG, new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div>\r\n                " +
"<div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 60 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
               Write(Html.LabelFor(Model=>Model.CurHangMucCongTrinh.KETCAU,"Kết cấu", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 63 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
               Write(Html.TextBoxFor(m => m.CurHangMucCongTrinh.KETCAU, new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 70 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
               Write(Html.LabelFor(Model=>Model.CurHangMucCongTrinh.NAMXAYDUNG,"Năm xây dựng", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 73 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
               Write(Html.TextBoxFor(m => m.CurHangMucCongTrinh.NAMXAYDUNG, new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div>\r\n                " +
"<div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 78 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
               Write(Html.LabelFor(Model=>Model.CurHangMucCongTrinh.NAMHOANTHANH,"Năm hoàn thành", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 81 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
               Write(Html.TextBoxFor(m => m.CurHangMucCongTrinh.NAMHOANTHANH, new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 88 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
               Write(Html.LabelFor(Model=>Model.CurHangMucCongTrinh.SOTANG,"Số tầng", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 91 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
               Write(Html.TextBoxFor(m => m.CurHangMucCongTrinh.SOTANG, new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div>\r\n                " +
"<div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 96 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
               Write(Html.LabelFor(Model=>Model.CurHangMucCongTrinh.SOTANGHAM,"Số tầng hầm", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 99 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
               Write(Html.TextBoxFor(m => m.CurHangMucCongTrinh.SOTANGHAM, new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 107 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
               Write(Html.LabelFor(Model=>Model.CurHangMucCongTrinh.THOIHANSOHUU,"Thời hạn sở hữu", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 110 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
               Write(Html.TextBoxFor(m => m.CurHangMucCongTrinh.THOIHANSOHUU, new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div>\r\n                " +
"<div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 115 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
               Write(Html.LabelFor(Model=>Model.CurHangMucCongTrinh.CAPHANG,"Cấp hạng", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 118 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
               Write(Html.TextBoxFor(m => m.CurHangMucCongTrinh.CAPHANG, new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 126 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
               Write(Html.LabelFor(Model => Model.CurHangMucCongTrinh.CONGNANG, "Công năng", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 129 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
               Write(Html.TextBoxFor(m => m.CurHangMucCongTrinh.CONGNANG, new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 135 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
           Write(Html.LabelFor(m => m.mota, "Mô tả", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 138 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
           Write(Html.TextBoxFor(m => m.mota, new { @class = "form-control input-sm " }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div>\r\n                <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 144 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
               Write(Html.LabelFor(Model => Model.CurHangMucCongTrinh.DIACHIID, "Địa chỉ", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 147 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
               Write(Html.TextAreaFor(m => m.CurHangMucCongTrinh.DIACHIID, new { @class = "form-control input-sm",@row="2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"clear\"");

WriteLiteral("></div>\r\n");

            
            #line 152 "..\..\Views\XLHSDangKy\_DonDangKy_HangMucCongTrinh.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n<script>\r\n\r\n</script>");

        }
    }
}
#pragma warning restore 1591
