#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MPLIS;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/XLHSDangKy/_Popup_KetQuaTimKiemCaNhan.cshtml")]
    public partial class _Views_XLHSDangKy__Popup_KetQuaTimKiemCaNhan_cshtml : System.Web.Mvc.WebViewPage<MPLIS.Libraries.Data.XuLyHoSo.Models.DSCaNhanVM>
    {
        public _Views_XLHSDangKy__Popup_KetQuaTimKiemCaNhan_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\'modal fade\'");

WriteLiteral(" id=\'modalKQTKCaNhanID\'");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 4 "..\..\Views\XLHSDangKy\_Popup_KetQuaTimKiemCaNhan.cshtml"
Write(Html.Hidden("Count", Model.DSCaNhan.Count, new { @id = "CountCaNhanID" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div");

WriteLiteral(" class=\'modal-dialog\'");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\'modal-content\'");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\'modal-header\'");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\'button\'");

WriteLiteral(" class=\'close\'");

WriteLiteral(" data-dismiss=\'modal\'");

WriteLiteral(">&times;</button>\r\n                <h4");

WriteLiteral(" class=\'modal-title\'");

WriteLiteral(">Kết quả tìm kiếm cá nhân</h4>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\'modal-body\'");

WriteLiteral(">\r\n                <table");

WriteLiteral(" id=\"TableDSCaNhanID\"");

WriteLiteral(" class=\"table table-bordered\"");

WriteLiteral(@">
                    <thead>
                        <tr>
                            <th></th>
                            <th>#</th>
                            <th>Họ tên</th>
                            <th>CMT / Hộ chiếu</th>
                            <th>Nơi cấp</th>
                            <th>Địa chỉ</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
");

            
            #line 25 "..\..\Views\XLHSDangKy\_Popup_KetQuaTimKiemCaNhan.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\XLHSDangKy\_Popup_KetQuaTimKiemCaNhan.cshtml"
                         if (Model.DSCaNhan != null && Model.DSCaNhan.Count > 0)
                        {
                            int sTT = 0;
                            foreach (var item in Model.DSCaNhan)
                            {
                                sTT++;

            
            #line default
            #line hidden
WriteLiteral("                                <tr>\r\n                                    <td>\r\n");

WriteLiteral("                                        ");

            
            #line 33 "..\..\Views\XLHSDangKy\_Popup_KetQuaTimKiemCaNhan.cshtml"
                                   Write(item.CANHANID);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                    " +
"<td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 36 "..\..\Views\XLHSDangKy\_Popup_KetQuaTimKiemCaNhan.cshtml"
                                   Write(sTT);

            
            #line default
            #line hidden
WriteLiteral(".\r\n                                    </td>\r\n                                   " +
" <td>\r\n");

WriteLiteral("                                        ");

            
            #line 39 "..\..\Views\XLHSDangKy\_Popup_KetQuaTimKiemCaNhan.cshtml"
                                   Write(item.HOTEN);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                    " +
"<td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 42 "..\..\Views\XLHSDangKy\_Popup_KetQuaTimKiemCaNhan.cshtml"
                                   Write(item.SOGIAYTO);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                    " +
"<td>\r\n");

WriteLiteral("                                        ");

            
            #line 45 "..\..\Views\XLHSDangKy\_Popup_KetQuaTimKiemCaNhan.cshtml"
                                   Write(item.NOICAP);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                    " +
"<td>\r\n");

WriteLiteral("                                        ");

            
            #line 48 "..\..\Views\XLHSDangKy\_Popup_KetQuaTimKiemCaNhan.cshtml"
                                   Write(item.DIACHI);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                    " +
"<td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("></td>\r\n                                </tr>\r\n");

            
            #line 52 "..\..\Views\XLHSDangKy\_Popup_KetQuaTimKiemCaNhan.cshtml"
                            }
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </tbody>\r\n                </table>\r\n            </div>\r\n     " +
"   </div>\r\n    </div>\r\n</div>\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    $(document).ready(function () {\r\n        var columns = [\r\n            { \"d" +
"ata\": \"CANHANID\" },\r\n            { \"data\": \"STT\" },\r\n            { \"data\": \"HOTE" +
"N\" },\r\n            { \"data\": \"SOGIAYTO\" },\r\n            { \"data\": \"NOICAP\" },\r\n " +
"           { \"data\": \"DIACHI\" },\r\n            { \"data\": null }\r\n        ]\r\n     " +
"   var columnDefs = [\r\n            {\r\n                \"targets\": 0,\r\n           " +
"     \"visible\": false\r\n            },\r\n            {\r\n                \"targets\":" +
" -1,\r\n                \"render\": function () {\r\n                    return \"<butt" +
"on type=\'button\' class=\'btn btn-xs btn-heading btnSel\'>Chọn</button>\";\r\n        " +
"        }\r\n            }\r\n        ]\r\n        var options = {\r\n            \"pageL" +
"ength\": 5,\r\n            \"lengthChange\": false,\r\n            \"ordering\": false,\r\n" +
"            \"info\": false,\r\n            \"searching\": false,\r\n            \"autoWi" +
"dth\": false,\r\n            \"language\": {\r\n                \"url\": \"https://cdn.dat" +
"atables.net/plug-ins/9dcbecd42ad/i18n/Vietnamese.json\"\r\n            },\r\n        " +
"    \"columns\": columns,\r\n            \"columnDefs\": columnDefs,\r\n            \"dom" +
"\": \'t<\"bottom\"p><\"clear\">\'\r\n        }\r\n\r\n        var TableDSCaNhanID = $(\'#Table" +
"DSCaNhanID\').DataTable(options);\r\n\r\n        TableDSCaNhanID.rows().nodes().on(\'c" +
"lick\', \'tbody tr\', function () {\r\n            if (TableDSCaNhanID.rows().nodes()" +
".length > 0) {\r\n                ChonCaNhan(TableDSCaNhanID.row($(this)).data());" +
"\r\n            }\r\n        })\r\n\r\n        TableDSCaNhanID.rows().nodes().on(\'click\'" +
", \'tbody tr button\', function (event) {\r\n            event.stopPropagation();\r\n " +
"       })\r\n\r\n        TableDSCaNhanID.rows().nodes().on(\'click\', \'tbody tr .btnSe" +
"l\', function (event) {\r\n            ChonCaNhan(TableDSCaNhanID.row($(this).paren" +
"ts(\'tr\')).data());\r\n        })\r\n\r\n        function ChonCaNhan(rowData) {\r\n      " +
"      //$.ajax({\r\n            //    type: \"POST\",\r\n            //    url: \"/XLHS" +
"DangKy/DonDangKy_ChonCaNhan\",\r\n            //    data: { caNhanID: rowData.CANHA" +
"NID },\r\n            //    dataType: \"html\",\r\n            //    success: function" +
" (result) {\r\n                    \r\n            //    }\r\n            //})\r\n      " +
"  }\r\n\r\n    })\r\n</script>\r\n");

        }
    }
}
#pragma warning restore 1591
