#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\XLHSDangKy\_Popup_TaiLieuDoDac.cshtml"
    using AppCore.Models;
    
    #line default
    #line hidden
    using MPLIS;
    
    #line 1 "..\..\Views\XLHSDangKy\_Popup_TaiLieuDoDac.cshtml"
    using MPLIS.Libraries.Data.XuLyHoSo.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/XLHSDangKy/_Popup_TaiLieuDoDac.cshtml")]
    public partial class _Views_XLHSDangKy__Popup_TaiLieuDoDac_cshtml : System.Web.Mvc.WebViewPage<DC_TAILIEUDODAC>
    {
        public _Views_XLHSDangKy__Popup_TaiLieuDoDac_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\'modal fade\'");

WriteLiteral(" id=\'modalformTaiLieuDoDacID\'");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\'modal-dialog modal-lg\'");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\'modal-content\'");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\'modal-header\'");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\'button\'");

WriteLiteral(" class=\'close\'");

WriteLiteral(" data-dismiss=\'modal\'");

WriteLiteral(">&times;</button>\r\n                <h4");

WriteLiteral(" class=\'modal-title\'");

WriteLiteral(">Chi tiết tài liệu đo đạc</h4>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\'modal-body\'");

WriteLiteral(">\r\n                <form");

WriteLiteral(" method=\"POST\"");

WriteLiteral(" id=\"Form_TaiLieuDoDac\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 14 "..\..\Views\XLHSDangKy\_Popup_TaiLieuDoDac.cshtml"
               Write(Html.HiddenFor(model => model.TAILIEUDODACID));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 15 "..\..\Views\XLHSDangKy\_Popup_TaiLieuDoDac.cshtml"
               Write(Html.HiddenFor(model => model.THUADATID));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 18 "..\..\Views\XLHSDangKy\_Popup_TaiLieuDoDac.cshtml"
                       Write(Html.LabelFor(model => model.LOAIBANDODIACHINHID, "Loại bản đồ địa chính", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-xs-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 21 "..\..\Views\XLHSDangKy\_Popup_TaiLieuDoDac.cshtml"
                       Write(Html.DropDownListFor(model => model.LOAIBANDODIACHINHID, new SelectList(ViewBag.loaibando, "LOAIBANDODIACHINHID", "TENLOAIBANDODIACHINH").ToList(), "--- Lựa chọn ---", new { @class = "form-control required", required = "required" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 24 "..\..\Views\XLHSDangKy\_Popup_TaiLieuDoDac.cshtml"
                       Write(Html.LabelFor(model => model.TENTAILIEU, "Tên tài liệu", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-xs-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 27 "..\..\Views\XLHSDangKy\_Popup_TaiLieuDoDac.cshtml"
                       Write(Html.TextBoxFor(model => model.TENTAILIEU, new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 32 "..\..\Views\XLHSDangKy\_Popup_TaiLieuDoDac.cshtml"
                       Write(Html.LabelFor(model => model.PHUONGPHAPDO, "Phương pháp đo", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-xs-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 35 "..\..\Views\XLHSDangKy\_Popup_TaiLieuDoDac.cshtml"
                       Write(Html.TextBoxFor(model => model.PHUONGPHAPDO, new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 38 "..\..\Views\XLHSDangKy\_Popup_TaiLieuDoDac.cshtml"
                       Write(Html.LabelFor(model => model.MUCDOCHINHXAC, "Mức độ chính xác", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-xs-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 41 "..\..\Views\XLHSDangKy\_Popup_TaiLieuDoDac.cshtml"
                       Write(Html.TextBoxFor(model => model.MUCDOCHINHXAC, new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 46 "..\..\Views\XLHSDangKy\_Popup_TaiLieuDoDac.cshtml"
                       Write(Html.LabelFor(model => model.TYLEDODAC, "Tỷ lệ đo đạc", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-xs-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 49 "..\..\Views\XLHSDangKy\_Popup_TaiLieuDoDac.cshtml"
                       Write(Html.TextBoxFor(model => model.TYLEDODAC, new { maxlength = "30", @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 52 "..\..\Views\XLHSDangKy\_Popup_TaiLieuDoDac.cshtml"
                       Write(Html.LabelFor(model => model.NGAYHOANTHANH, "Ngày hoàn thành", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-xs-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 55 "..\..\Views\XLHSDangKy\_Popup_TaiLieuDoDac.cshtml"
                       Write(Html.TextBoxFor(model => model.NGAYHOANTHANH, "{0:yyyy-MM-dd}", new { @type = "date", @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </f" +
"orm>\r\n            </div> \r\n            <div");

WriteLiteral(" class=\'modal-footer\'");

WriteLiteral(" style=\'text-align:center;\'");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\'button\'");

WriteLiteral(" class=\'btn btn-primary btn-sm pull-right\'");

WriteLiteral(">Làm mới</button>\r\n                <button");

WriteLiteral(" type=\'button\'");

WriteLiteral(" class=\'btn btn-primary btn-sm pull-right\'");

WriteLiteral(">Cập nhật</button>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<sc" +
"ript>\r\n\r\n\r\n    $(function () {\r\n        $(\"#btncapnhattailieudodac\").on(\"click\"," +
" function () {\r\n            var formdata = $(\"#Form_TaiLieuDoDac\").serializeArra" +
"y();\r\n            $.ajax({\r\n                type: \"POST\",\r\n                url: " +
"\"/XLHSDangKy/SaveDoDac\",\r\n                data: formdata,\r\n                dataT" +
"ype: \"html\",\r\n                success: function (data) {\r\n\r\n                    " +
"$(\'#div_tailieudodac\').html(data);\r\n                    alert(\'Lưu tài liệu th" +
"ành công\');\r\n                    alert($(\'#formtailieudodacid\').val());\r\n      " +
"              alert($(\'#formThuaid\').val());\r\n                    $(\'#THUADATID\'" +
").val($(\'#formThuaid\').val());\r\n                    $(\'#TAILIEUDODACID\').val($(\'" +
"#formtailieudodacid\').val());\r\n                    $(\'#TENTAILIEUDD\').val($(\'#TE" +
"NTAILIEU\').val());\r\n                }\r\n            });\r\n\r\n        });\r\n\r\n\r\n     " +
"   $(\"#btnthemmoitailieudodac\").on(\"click\", function () {\r\n            var thuai" +
"d = $(\'#hi_ThuaId\').val();\r\n            $.ajax({\r\n                type: \"POST\",\r" +
"\n                url: \"/XLHSDangKy/LamMoiDoDac\",\r\n                data: { THUAID" +
": thuaid.trim() },\r\n                dataType: \"html\",\r\n                success: " +
"function (data) {\r\n                    $(\'#div_tailieudodac\').html(data);\r\n     " +
"               //alert($(\'#THUADATID\').val());\r\n                    //$(\'#hi_Thu" +
"aId\').val($(\'#THUADATID\').val());\r\n                }\r\n            });\r\n        }" +
");\r\n\r\n    });\r\n</script>\r\n");

        }
    }
}
#pragma warning restore 1591
