#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MPLIS;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/XLHSDangKy/_Popup_KetQuaTimKiemVoChong.cshtml")]
    public partial class _Views_XLHSDangKy__Popup_KetQuaTimKiemVoChong_cshtml : System.Web.Mvc.WebViewPage<MPLIS.Libraries.Data.XuLyHoSo.Models.DSVoChongVM>
    {
        public _Views_XLHSDangKy__Popup_KetQuaTimKiemVoChong_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\'modal fade\'");

WriteLiteral(" id=\'modalKQTKVoChongID\'");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 4 "..\..\Views\XLHSDangKy\_Popup_KetQuaTimKiemVoChong.cshtml"
Write(Html.Hidden("Count", Model.DSVoChong.Count, new { @id = "CountVoChongID" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div");

WriteLiteral(" class=\'modal-dialog\'");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\'modal-content\'");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\'modal-header\'");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\'button\'");

WriteLiteral(" class=\'close\'");

WriteLiteral(" data-dismiss=\'modal\'");

WriteLiteral(">&times;</button>\r\n                <h4");

WriteLiteral(" class=\'modal-title\'");

WriteLiteral(">Kết quả tìm kiếm vợ chồng</h4>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\'modal-body\'");

WriteLiteral(">\r\n                <table");

WriteLiteral(" id=\"TableDSVoChongID\"");

WriteLiteral(" class=\"table table-bordered\"");

WriteLiteral(@">
                    <thead>
                        <tr>
                            <th></th>
                            <th>#</th>
                            <th>Chồng</th>
                            <th>CMT chồng</th>
                            <th>Vợ</th>
                            <th>CMT vợ</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
");

            
            #line 25 "..\..\Views\XLHSDangKy\_Popup_KetQuaTimKiemVoChong.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\XLHSDangKy\_Popup_KetQuaTimKiemVoChong.cshtml"
                         if (Model.DSVoChong != null && Model.DSVoChong.Count > 0)
                        {
                            int sTT = 0;
                            foreach (var item in Model.DSVoChong)
                            {
                                sTT++;

            
            #line default
            #line hidden
WriteLiteral("                                <tr>\r\n                                    <td>\r\n");

WriteLiteral("                                        ");

            
            #line 33 "..\..\Views\XLHSDangKy\_Popup_KetQuaTimKiemVoChong.cshtml"
                                   Write(item.VOCHONGID);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                    " +
"<td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 36 "..\..\Views\XLHSDangKy\_Popup_KetQuaTimKiemVoChong.cshtml"
                                   Write(sTT);

            
            #line default
            #line hidden
WriteLiteral(".\r\n                                    </td>\r\n                                   " +
" <td>\r\n");

WriteLiteral("                                        ");

            
            #line 39 "..\..\Views\XLHSDangKy\_Popup_KetQuaTimKiemVoChong.cshtml"
                                   Write(item.ChongCN.HOTEN);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                    " +
"<td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 42 "..\..\Views\XLHSDangKy\_Popup_KetQuaTimKiemVoChong.cshtml"
                                   Write(item.CMTCHONG);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                    " +
"<td>\r\n");

WriteLiteral("                                        ");

            
            #line 45 "..\..\Views\XLHSDangKy\_Popup_KetQuaTimKiemVoChong.cshtml"
                                   Write(item.VoCN.HOTEN);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                    " +
"<td>\r\n");

WriteLiteral("                                        ");

            
            #line 48 "..\..\Views\XLHSDangKy\_Popup_KetQuaTimKiemVoChong.cshtml"
                                   Write(item.CMTVO);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                    " +
"<td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("></td>\r\n                                </tr>\r\n");

            
            #line 52 "..\..\Views\XLHSDangKy\_Popup_KetQuaTimKiemVoChong.cshtml"
                            }
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </tbody>\r\n                </table>\r\n            </div>\r\n     " +
"   </div>\r\n    </div>\r\n</div>\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    $(document).ready(function () {\r\n        var columns = [\r\n            { \"d" +
"ata\": \"VOCHONGID\" },\r\n            { \"data\": \"STT\" },\r\n            { \"data\": \"CHO" +
"NGHOTEN\" },\r\n            { \"data\": \"CMTCHONG\" },\r\n            { \"data\": \"VOHOTEN" +
"\" },\r\n            { \"data\": \"CMTVO\" },\r\n            { \"data\": null }\r\n        ]\r" +
"\n        var columnDefs = [\r\n            {\r\n                \"targets\": 0,\r\n     " +
"           \"visible\": false\r\n            },\r\n            {\r\n                \"tar" +
"gets\": -1,\r\n                \"render\": function () {\r\n                    return " +
"\"<button type=\'button\' class=\'btn btn-xs btn-heading btnSel\'>Chọn</button>\";\r\n  " +
"              }\r\n            }\r\n        ]\r\n        var options = {\r\n            " +
"\"pageLength\": 5,\r\n            \"lengthChange\": false,\r\n            \"ordering\": fa" +
"lse,\r\n            \"info\": false,\r\n            \"searching\": false,\r\n            \"" +
"autoWidth\": false,\r\n            \"language\": {\r\n                \"url\": \"https://c" +
"dn.datatables.net/plug-ins/9dcbecd42ad/i18n/Vietnamese.json\"\r\n            },\r\n  " +
"          \"columns\": columns,\r\n            \"columnDefs\": columnDefs,\r\n          " +
"  \"dom\": \'t<\"bottom\"p><\"clear\">\'\r\n        }\r\n        var TableDSVoChongID = $(\'#" +
"TableDSVoChongID\').DataTable(options);\r\n\r\n        TableDSVoChongID.rows().nodes(" +
").on(\'click\', \'tbody tr\', function () {\r\n            if (TableDSVoChongID.rows()" +
".nodes().length > 0) {\r\n                ChonVoChong(TableDSVoChongID.row($(this)" +
").data());\r\n                //if ($(TableDSCaNhanID.row(this).node()).attr(\'clas" +
"s\').indexOf(\'activerow\') != -1) {\r\n                //    $(TableDSCaNhanID.row(t" +
"his).node()).removeClass(\'activerow\');\r\n                //} else {\r\n            " +
"    //    $(TableDSCaNhanID.rows().nodes()).removeClass(\'activerow\');\r\n         " +
"       //    $(TableDSCaNhanID.row(this).node()).addClass(\'activerow\');\r\n       " +
"         //}\r\n            }\r\n        })\r\n\r\n        TableDSVoChongID.rows().nodes" +
"().on(\'click\', \'tbody tr button\', function (event) {\r\n            event.stopProp" +
"agation();\r\n        })\r\n\r\n        TableDSVoChongID.rows().nodes().on(\'click\', \'t" +
"body tr .btnSel\', function (event) {\r\n            ChonVoChong(TableDSVoChongID.r" +
"ow($(this).parents(\'tr\')).data());\r\n        })\r\n\r\n        function ChonVoChong(r" +
"owData) {\r\n            console.log(\"Chọn vợ chồng!\");\r\n            console.log(r" +
"owData);\r\n            $.ajax({\r\n                type: \"POST\",\r\n                u" +
"rl: \"/XLHSDangKy/DonDangKy_ChonVoChong\",\r\n                data: { voChongID: row" +
"Data.VOCHONGID },\r\n                dataType: \"html\",\r\n                success: f" +
"unction (result) {\r\n                    $(\'#divCTChuVCID\')\r\n                    " +
"    .html(result)\r\n                        .ready(function () {\r\n               " +
"             $(\"#modalKQTKVoChongID\").modal(\'hide\');\r\n                        })" +
"\r\n                }\r\n            })\r\n        }\r\n\r\n    })\r\n</script>\r\n");

        }
    }
}
#pragma warning restore 1591
