#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MPLIS;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/XLHSDangKy/DanhSachChu_ChiTietChu.cshtml")]
    public partial class _Views_XLHSDangKy_DanhSachChu_ChiTietChu_cshtml : System.Web.Mvc.WebViewPage<MPLIS.Libraries.Data.XuLyHoSo.Models.DangKy_NguoiLS>
    {
        public _Views_XLHSDangKy_DanhSachChu_ChiTietChu_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" id=\"FormChiTietChuID\"");

WriteLiteral(" class=\"box box-primary m-0\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" id=\"formNguoiID\"");

WriteLiteral(" class=\"d-none\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 5 "..\..\Views\XLHSDangKy\DanhSachChu_ChiTietChu.cshtml"
   Write(Html.Hidden("NGUOIID", Model.Chu.NGUOIID));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 6 "..\..\Views\XLHSDangKy\DanhSachChu_ChiTietChu.cshtml"
   Write(Html.Hidden("CHITIETID", Model.Chu.CHITIETID));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 7 "..\..\Views\XLHSDangKy\DanhSachChu_ChiTietChu.cshtml"
   Write(Html.Hidden("DOITUONGSUDUNGID", Model.Chu.DOITUONGSUDUNGID));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 8 "..\..\Views\XLHSDangKy\DanhSachChu_ChiTietChu.cshtml"
   Write(Html.Hidden("TRANGTHAI", Model.Chu.TRANGTHAI));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 9 "..\..\Views\XLHSDangKy\DanhSachChu_ChiTietChu.cshtml"
   Write(Html.Hidden("LOAIDOITUONGID", Model.Chu.LOAIDOITUONGID));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </form>\r\n    <div");

WriteLiteral(" class=\"box-header with-border\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row p-0\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-4 p-0\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n");

            
            #line 15 "..\..\Views\XLHSDangKy\DanhSachChu_ChiTietChu.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\XLHSDangKy\DanhSachChu_ChiTietChu.cshtml"
                     if (Model.TRANGTHAI == 1)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <button");

WriteLiteral(" id=\"BtnSave_FormChiTietChuID\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-sm btn-default\"");

WriteLiteral("><i");

WriteLiteral(" class=\'fa fa-plus\'");

WriteLiteral("></i> Thêm mới</button>\r\n");

            
            #line 18 "..\..\Views\XLHSDangKy\DanhSachChu_ChiTietChu.cshtml"
                    }
                    else if (Model.TRANGTHAI == 2)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <button");

WriteLiteral(" id=\"BtnSave_FormChiTietChuID\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-sm btn-default\"");

WriteLiteral("><i");

WriteLiteral(" class=\'fa fa-check\'");

WriteLiteral("></i> Lưu thông tin</button>\r\n");

            
            #line 22 "..\..\Views\XLHSDangKy\DanhSachChu_ChiTietChu.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <button");

WriteLiteral(" id=\"BtnClear_FormChiTietChuID\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-sm btn-default\"");

WriteLiteral("><i");

WriteLiteral(" class=\'fa fa-trash\'");

WriteLiteral("></i> Xóa trắng</button>\r\n                </div>\r\n            </div>\r\n           " +
" <div");

WriteLiteral(" class=\"col-xs-4 text-center p-0\"");

WriteLiteral(">\r\n");

            
            #line 27 "..\..\Views\XLHSDangKy\DanhSachChu_ChiTietChu.cshtml"
                
            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\XLHSDangKy\DanhSachChu_ChiTietChu.cshtml"
                  
                    string title = "";
                    switch (Model.Chu.LOAIDOITUONGID)
                    {
                        case "1":
                            title = "Cá Nhân";
                            break;
                        case "2":
                            title = "Hộ Gia Đình";
                            break;
                        case "3":
                            title = "Vợ Chồng";
                            break;
                        case "4":
                            title = "Tổ Chức";
                            break;
                        case "5":
                            title = "Cộng Đồng";
                            break;
                        case "6":
                            title = "Nhóm Người";
                            break;
                        default:
                            break;
                    }
                
            
            #line default
            #line hidden
WriteLiteral("\r\n                <h3");

WriteLiteral(" class=\"box-title\"");

WriteLiteral(">Thông tin chi tiết ");

            
            #line 53 "..\..\Views\XLHSDangKy\DanhSachChu_ChiTietChu.cshtml"
                                                    Write(Html.Raw(title));

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-4 p-0\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row p-0\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-xs-3 p-0\"");

WriteLiteral(">\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"col-xs-6 p-0\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 61 "..\..\Views\XLHSDangKy\DanhSachChu_ChiTietChu.cshtml"
                       Write(Html.DropDownListFor(model => model.Chu.DOITUONGSUDUNGID, new SelectList(ViewBag.dSDoiTuongSuDung, "DOITUONGSUDUNGID", "TENDOITUONGSUDUNG"), "---- Chọn đối tượng sử dụng ----", new { @class = "input-sm form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" class=\"col-xs-3 p-0\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" id=\"BtnClose_FormChiTietChuID\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-box-tool\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-remove\"");

WriteLiteral("></i></button>\r\n                        </div>\r\n                    </div>\r\n     " +
"           </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"box-body p-0\"");

WriteLiteral(">\r\n");

            
            #line 74 "..\..\Views\XLHSDangKy\DanhSachChu_ChiTietChu.cshtml"
        
            
            #line default
            #line hidden
            
            #line 74 "..\..\Views\XLHSDangKy\DanhSachChu_ChiTietChu.cshtml"
          
            switch (Model.Chu.LOAIDOITUONGID)
            {
                case "1":
                    
            
            #line default
            #line hidden
            
            #line 78 "..\..\Views\XLHSDangKy\DanhSachChu_ChiTietChu.cshtml"
               Write(Html.Partial("ChiTietChu_CaNhan", Model.Chu.CaNhan));

            
            #line default
            #line hidden
            
            #line 78 "..\..\Views\XLHSDangKy\DanhSachChu_ChiTietChu.cshtml"
                                                                        
                    break;
                case "2":
                    
            
            #line default
            #line hidden
            
            #line 81 "..\..\Views\XLHSDangKy\DanhSachChu_ChiTietChu.cshtml"
               Write(Html.Partial("ChiTietChu_HoGiaDinh", Model.Chu.HoGiaDinh));

            
            #line default
            #line hidden
            
            #line 81 "..\..\Views\XLHSDangKy\DanhSachChu_ChiTietChu.cshtml"
                                                                              
                    break;
                case "3":

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" id=\"divChiTietChu_VoChongID\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 85 "..\..\Views\XLHSDangKy\DanhSachChu_ChiTietChu.cshtml"
                   Write(Html.Partial("ChiTietChu_VoChong", Model.Chu.VoChong));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n");

            
            #line 87 "..\..\Views\XLHSDangKy\DanhSachChu_ChiTietChu.cshtml"
                    break;
                case "4":

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" id=\"divChiTietChu_ToChucID\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 90 "..\..\Views\XLHSDangKy\DanhSachChu_ChiTietChu.cshtml"
                   Write(Html.Partial("ChiTietChu_ToChuc", Model.Chu.ToChuc));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n");

            
            #line 92 "..\..\Views\XLHSDangKy\DanhSachChu_ChiTietChu.cshtml"
                    break;
                case "5":

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" id=\"divChiTietChu_CongDongID\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 95 "..\..\Views\XLHSDangKy\DanhSachChu_ChiTietChu.cshtml"
                   Write(Html.Partial("ChiTietChu_CongDong", Model.Chu.CongDong));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n");

            
            #line 97 "..\..\Views\XLHSDangKy\DanhSachChu_ChiTietChu.cshtml"
                    break;
                case "6":

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" id=\"divChiTietChu_NhomNguoiID\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 100 "..\..\Views\XLHSDangKy\DanhSachChu_ChiTietChu.cshtml"
                   Write(Html.Partial("ChiTietChu_NhomNguoi", Model.Chu.NhomNguoi));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n");

            
            #line 102 "..\..\Views\XLHSDangKy\DanhSachChu_ChiTietChu.cshtml"
                    break;
                default:
                    break;
            }
        
            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">

        $(document).ready(function () {

            $('#BtnClose_FormChiTietChuID').on('click', function () {
                $('#FormChiTietChuID').siblings().removeClass(""d-none"");
                $('#FormChiTietChuID').remove();
            })

            $('#BtnSave_FormChiTietChuID').on('click', function () {
                var objNguoi = FormToObject($('#formNguoiID'));
                var checkSubmit = false;
                switch ('");

            
            #line 121 "..\..\Views\XLHSDangKy\DanhSachChu_ChiTietChu.cshtml"
                    Write(Model.Chu.LOAIDOITUONGID);

            
            #line default
            #line hidden
WriteLiteral("\') {\r\n                    case \"1\":\r\n                        var TableGiayToID = " +
"$(\'#TableGiayToID\').DataTable();\r\n                        var dSGiayTo = [];\r\n  " +
"                      $.each(TableGiayToID.rows().nodes(), function () {\r\n      " +
"                      var curRow = TableGiayToID.row(this).data();\r\n            " +
"                var objGiayTo = {};\r\n                            for (var temp i" +
"n curRow) {\r\n                                objGiayTo[temp] = curRow[temp];\r\n  " +
"                          }\r\n                            dSGiayTo.push(objGiayTo" +
");\r\n                        })\r\n                        for (var temp in dSGiayT" +
"o) {\r\n                            if (dSGiayTo[temp][\"LAGIAYTOINGCN\"] == \"True\")" +
" {\r\n                                dSGiayTo[temp][\"LAGIAYTOINGCN\"] = \"true\";\r\n " +
"                           } else {\r\n                                dSGiayTo[te" +
"mp][\"LAGIAYTOINGCN\"] = \"false\";\r\n                            }\r\n                " +
"            dSGiayTo[temp][\"NGAYCAP\"] = ConverDatatime(dSGiayTo[temp][\"NGAYCAP\"]" +
");\r\n                            delete dSGiayTo[temp][\"STT\"];\r\n                 " +
"           delete dSGiayTo[temp][\"TenLoaiGiayTo\"];\r\n                            " +
"delete dSGiayTo[temp][\"TRANGTHAI\"];\r\n                        }\r\n                " +
"        objNguoi[\"CaNhan\"] = FormToObject($(\'#formTTCaNhanID\'));\r\n              " +
"          objNguoi[\"CaNhan\"][\"DSGiayToTuyThan\"] = dSGiayTo;\r\n                   " +
"     checkSubmit = true;\r\n                        break;\r\n                    ca" +
"se \"2\":\r\n                        if ($(\'#formTTHoGiaDinhID [name=CHUHO]\').val() " +
"== \"\") {\r\n                            alert(\"Vui lòng thêm Chủ Hộ cho Hộ Gia Đìn" +
"h!\");\r\n                        } else {\r\n                            $(\'#formTTH" +
"oGiaDinhID [name=CMTCHUHO]\').prop(\'disabled\', false);\r\n                         " +
"   $(\'#formTTHoGiaDinhID [name=CMTVOCHONG]\').prop(\'disabled\', false);\r\n         " +
"                   objNguoi[\"HoGiaDinh\"] = FormToObject($(\'#formTTHoGiaDinhID\'))" +
";\r\n                            $(\'#formTTHoGiaDinhID [name=CMTCHUHO]\').prop(\'dis" +
"abled\', true);\r\n                            $(\'#formTTHoGiaDinhID [name=CMTVOCHO" +
"NG]\').prop(\'disabled\', true);\r\n                            checkSubmit = true;\r\n" +
"                        }\r\n                        break;\r\n                    c" +
"ase \"3\":\r\n                        if ($(\'#formTTVoChongID [name=CHONG]\').val() =" +
"= \"\") {\r\n                            alert(\"Vui lòng thêm Chồng cho chủ Vợ Chồng" +
"!\");\r\n                        } else if ($(\'#formTTVoChongID [name=VO]\').val() =" +
"= \"\") {\r\n                            alert(\"Vui lòng thêm Vợ cho chủ Vợ Chồng!\")" +
";\r\n                        } else {\r\n                            $(\'#formTTVoCho" +
"ngID [name=CMTCHONG]\').prop(\'disabled\', false);\r\n                            $(\'" +
"#formTTVoChongID [name=CMTVO]\').prop(\'disabled\', false);\r\n                      " +
"      objNguoi[\"VoChong\"] = FormToObject($(\'#formTTVoChongID\'));\r\n              " +
"              $(\'#formTTVoChongID [name=CMTCHONG]\').prop(\'disabled\', true);\r\n   " +
"                         $(\'#formTTVoChongID [name=CMTVO]\').prop(\'disabled\', tru" +
"e);\r\n                            checkSubmit = true;\r\n                        }\r" +
"\n                        break;\r\n                    case \"4\":\r\n                " +
"        if ($(\'#formTTToChucID [name=NGUOIDAIDIENID]\').val() == \"\") {\r\n         " +
"                   alert(\"Vui lòng thêm Người Đại Diện cho chủ Tổ Chức!\")\r\n     " +
"                   } else {\r\n                            $(\'#formTTToChucID [nam" +
"e=CMTNGUOIDAIDIEN]\').prop(\'disabled\', false);\r\n                            $(\'#f" +
"ormTTToChucID [name=LOAITOCHUC]\').prop(\'disabled\', false);\r\n                    " +
"        objNguoi[\"ToChuc\"] = FormToObject($(\'#formTTToChucID\'));\r\n              " +
"              $(\'#formTTToChucID [name=CMTNGUOIDAIDIEN]\').prop(\'disabled\', true)" +
";\r\n                            $(\'#formTTToChucID [name=LOAITOCHUC]\').prop(\'disa" +
"bled\', true);\r\n                            checkSubmit = true;\r\n                " +
"        }\r\n                        break;\r\n                    case \"5\":\r\n      " +
"                  if ($(\'#formTTCongDongID [name=NGUOIDAIDIENID]\').val() == \"\") " +
"{\r\n                            alert(\"Vui lòng thêm Người Đại Diện cho chủ Cộng " +
"Đồng!\")\r\n                        } else {\r\n                            $(\'#formT" +
"TCongDongID [name=CMTNGUOIDAIDIEN]\').prop(\'disabled\', false);\r\n                 " +
"           objNguoi[\"CongDong\"] = FormToObject($(\'#formTTCongDongID\'));\r\n       " +
"                     $(\'#formTTCongDongID [name=CMTNGUOIDAIDIEN]\').prop(\'disable" +
"d\', true);\r\n                            checkSubmit = true;\r\n                   " +
"     }\r\n                        break;\r\n                    case \"6\":\r\n         " +
"               if ($(\'#formTTNhomNguoiID [name=NGUOIDAIDIEN]\').val() == \"\") {\r\n " +
"                           alert(\"Vui lòng thêm Người Đại Diện cho chủ Nhóm Ngườ" +
"i!\")\r\n                        } else {\r\n                            $(\'#formTTNh" +
"omNguoiID [name=CMTNGUOIDAIDIEN]\').prop(\'disabled\', false);\r\n                   " +
"         objNguoi[\"NhomNguoi\"] = FormToObject($(\'#formTTNhomNguoiID\'));\r\n       " +
"                     $(\'#formTTNhomNguoiID [name=CMTNGUOIDAIDIEN]\').prop(\'disabl" +
"ed\', true);\r\n                            checkSubmit = true;\r\n                  " +
"      }\r\n                        break;\r\n                    default:\r\n         " +
"               break;\r\n                }\r\n                console.log(objNguoi);" +
"\r\n                if (checkSubmit) {\r\n                    $.ajax({\r\n            " +
"            type: \"POST\",\r\n                        url: \'/XLHSDangKy/Save_FormCh" +
"iTietChu\',\r\n                        data: { data: JSON.stringify(objNguoi) },\r\n " +
"                       dataType: \"json\",\r\n                        success: funct" +
"ion (result) {\r\n                            console.log(result);\r\n              " +
"              if (result.success) {\r\n                                if (\'");

            
            #line 219 "..\..\Views\XLHSDangKy\DanhSachChu_ChiTietChu.cshtml"
                                Write(Model.TRANGTHAI);

            
            #line default
            #line hidden
WriteLiteral("\' == \'1\') {\r\n                                    $(\'#BtnClear_FormChiTietChuID\')." +
"click();\r\n                                }\r\n                                var" +
" DangKyTableChuID = $(\'#DangKyTableChuID\').DataTable();\r\n                       " +
"         var objDangKyNguoi = null;\r\n                                var rowEle " +
"= null;\r\n                                $.each(DangKyTableChuID.rows().nodes()," +
" function () {\r\n                                    var curRow = DangKyTableChuI" +
"D.row(this).data();\r\n                                    if (curRow.DANGKYNGUOII" +
"D == result.obj.DANGKYNGUOIID) {\r\n                                        objDan" +
"gKyNguoi = DangKyTableChuID.row(this).data();\r\n                                 " +
"       rowEle = this;\r\n                                        return false;\r\n  " +
"                                  }\r\n                                })\r\n       " +
"                         if (objDangKyNguoi != null) {\r\n                        " +
"            result.obj.STT = DangKyTableChuID.row(rowEle).data().STT;\r\n         " +
"                           DangKyTableChuID.row(rowEle).data(result.obj).draw();" +
"\r\n                                } else {\r\n                                    " +
"result.obj.STT = DangKyTableChuID.data().count() + 1;\r\n                         " +
"           result.obj.STT += \".\";\r\n                                    DangKyTab" +
"leChuID.row.add(result.obj).draw();\r\n                                }\r\n        " +
"                    }\r\n                            alert(result.mes);\r\n         " +
"               }\r\n                    })\r\n                }\r\n            })\r\n\r\n " +
"           $(\'#BtnClear_FormChiTietChuID\').on(\'click\', function () {\r\n          " +
"      $.ajax({\r\n                    type: \"POST\",\r\n                    url: \'/XL" +
"HSDangKy/ChiTietChu_XoaTrang\',\r\n                    dataType: \"html\",\r\n         " +
"           success: function (html) {\r\n                        $(\'#FormChiTietCh" +
"uID\').remove();\r\n                        $(\'.box-body\').has(\'#DangKyTableChuID_w" +
"rapper\').append(html);\r\n                    }\r\n                })\r\n            }" +
")\r\n\r\n            $(\'#Chu_DOITUONGSUDUNGID\').on(\'change\', function () {\r\n        " +
"        $(\'#formNguoiID [name=DOITUONGSUDUNGID]\').val($(\'#Chu_DOITUONGSUDUNGID\')" +
".val());\r\n                $(\'#formTTToChucID [name=LOAITOCHUC]\').val($(\'#Chu_DOI" +
"TUONGSUDUNGID\').val()).change();\r\n            })\r\n\r\n        })\r\n\r\n    </script>\r" +
"\n\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
