#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MPLIS;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/XLHSDangKy/Form_DanhSachChu.cshtml")]
    public partial class _Views_XLHSDangKy_Form_DanhSachChu_cshtml : System.Web.Mvc.WebViewPage<MPLIS.Libraries.Data.XuLyHoSo.Models.DSChuDonVM>
    {
        public _Views_XLHSDangKy_Form_DanhSachChu_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"box box-primary\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"box-header with-border\"");

WriteLiteral(">\r\n        <h3");

WriteLiteral(" class=\"box-title\"");

WriteLiteral(">Chủ trong đăng ký</h3>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"box-body\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" id=\"DangKyTableChuID\"");

WriteLiteral(" class=\"table table-bordered\"");

WriteLiteral(@">
            <thead>
                <tr>
                    <th></th>
                    <th></th>
                    <th>#</th>
                    <th>Loại chủ</th>
                    <th>Tên chủ</th>
                    <th>CMT/Hộ chiếu</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
");

            
            #line 21 "..\..\Views\XLHSDangKy\Form_DanhSachChu.cshtml"
                
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\XLHSDangKy\Form_DanhSachChu.cshtml"
                 if (Model.DSDangKyChu != null && Model.DSDangKyChu.Count > 0)
                {
                    int sTT = 0;
                    foreach (var item in Model.DSDangKyChu)
                    {
                        sTT++;

            
            #line default
            #line hidden
WriteLiteral("                        <tr>\r\n                            <td>\r\n");

WriteLiteral("                                ");

            
            #line 29 "..\..\Views\XLHSDangKy\Form_DanhSachChu.cshtml"
                           Write(item.LOAI);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                            <td>\r\n");

WriteLiteral("                                ");

            
            #line 32 "..\..\Views\XLHSDangKy\Form_DanhSachChu.cshtml"
                           Write(item.DANGKYNGUOIID);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                            <td>\r\n");

WriteLiteral("                                ");

            
            #line 35 "..\..\Views\XLHSDangKy\Form_DanhSachChu.cshtml"
                           Write(sTT);

            
            #line default
            #line hidden
WriteLiteral(".\r\n                            </td>\r\n                            <td>\r\n");

WriteLiteral("                                ");

            
            #line 38 "..\..\Views\XLHSDangKy\Form_DanhSachChu.cshtml"
                           Write(item.Chu_TenLoaiChu);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                            <td>\r\n");

WriteLiteral("                                ");

            
            #line 41 "..\..\Views\XLHSDangKy\Form_DanhSachChu.cshtml"
                           Write(item.Chu_HoTen);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                            <td>\r\n");

WriteLiteral("                                ");

            
            #line 44 "..\..\Views\XLHSDangKy\Form_DanhSachChu.cshtml"
                           Write(item.Chu_CMT);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                            <td></td>\r\n     " +
"                   </tr>\r\n");

            
            #line 48 "..\..\Views\XLHSDangKy\Form_DanhSachChu.cshtml"
                    }
                }

            
            #line default
            #line hidden
WriteLiteral("            </tbody>\r\n        </table>\r\n    </div>\r\n    <button");

WriteLiteral(" id=\"btnThemChuID\"");

WriteLiteral(" class=\"btn btn-sm btn-default\"");

WriteLiteral("><i");

WriteLiteral(" class=\'fa fa-plus\'");

WriteLiteral("></i> Thêm mới</button>\r\n");

WriteLiteral("    ");

            
            #line 54 "..\..\Views\XLHSDangKy\Form_DanhSachChu.cshtml"
Write(Html.DropDownList("LoaiChuID", new SelectList(ViewBag.dSLoaiChu, "LOAICHUID", "TENLOAICHU"), "---- Chọn loại chủ ----", new { @class = "form-control input-sm", @id = "CBLOAICHUID" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    $(document).ready(function () {\r\n\r\n        var divProcessBar = \"<div class" +
"=\'overlay\'> <i class=\'fa fa-refresh fa-spin\'></i> </div>\";\r\n\r\n        var column" +
"s = [\r\n            { \"data\": \"LOAI\" },\r\n            { \"data\": \"DANGKYNGUOIID\" }," +
"\r\n            { \"data\": \"STT\" },\r\n            { \"data\": \"TENLOAICHU\" },\r\n       " +
"     { \"data\": \"TENCHU\" },\r\n            { \"data\": \"CMT\" },\r\n            { \"data\"" +
": null }\r\n        ]\r\n\r\n        var columnDefs = [\r\n            {\r\n              " +
"  \"targets\": [0, 1],\r\n                \"visible\": false\r\n            },\r\n        " +
"    {\r\n                \"targets\": -1,\r\n                \"render\": function () {\r\n" +
"                    return \"<button type=\'button\' class=\'btn btn-xs btn-heading " +
"btnDel\'>Xóa</button>\";\r\n                }\r\n            },\r\n            {\r\n      " +
"          \"targets\": [2],\r\n                \"className\": \"text-right\"\r\n          " +
"  },\r\n            {\r\n                \"targets\": [-1],\r\n                \"classNam" +
"e\": \"text-center\"\r\n            }\r\n        ]\r\n\r\n        var options = {\r\n        " +
"    \"pageLength\": 5,\r\n            \"ordering\": false,\r\n            \"autoWidth\": f" +
"alse,\r\n            \"columns\": columns,\r\n            \"columnDefs\": columnDefs,\r\n " +
"           \"dom\": \"t<\'row p-0\'<\'col-xs-6 p-0\'<\'row p-0\'<\'col-xs-6 p-0\'<\'#divCBID" +
"\'>><\'col-xs-6 p-0\' <\'#divBTID\'>>>><\'col-xs-6 p-0\'<\'pull-right\'p>>>\",\r\n          " +
"  \"initComplete\": function () {\r\n                initComplete();\r\n            }\r" +
"\n        }\r\n\r\n        function initComplete() {\r\n            $(\'#btnThemChuID\')." +
"appendTo($(\'#divBTID\'));\r\n            $(\'#CBLOAICHUID\').appendTo($(\'#divCBID\'));" +
"\r\n        }\r\n\r\n        var DangKyTableChuID = $(\'#DangKyTableChuID\').DataTable(o" +
"ptions);\r\n\r\n        DangKyTableChuID.on(\'draw\', function () {\r\n            $(\'#D" +
"angKyTableChuID_paginate\').appendTo($(\'#divDangKyTableChuID_paginateID\'));\r\n    " +
"    })\r\n\r\n        DangKyTableChuID.rows().nodes().on(\'dblclick\', \'tbody tr\', fun" +
"ction () {\r\n            if (DangKyTableChuID.rows().nodes().length > 0) {\r\n     " +
"           $(\'#CBLOAICHUID\').val(DangKyTableChuID.row($(this)).data().LOAI);\r\n  " +
"              XemTTChiTietChu(DangKyTableChuID.row($(this)).data(), $(this));\r\n " +
"           }\r\n        })\r\n\r\n        DangKyTableChuID.rows().nodes().on(\'click\', " +
"\'tbody tr button\', function (event) {\r\n            event.stopPropagation();\r\n   " +
"     })\r\n\r\n        DangKyTableChuID.rows().nodes().on(\'click\', \'tbody tr .btnDel" +
"\', function (event) {\r\n            XoaChuKhoiDangKy(DangKyTableChuID, DangKyTabl" +
"eChuID.row($(this).parents(\'tr\')).data(), DangKyTableChuID.row($(this).parents(\'" +
"tr\')));\r\n        })\r\n\r\n        function XemTTChiTietChu(rowData, eDom) {\r\n      " +
"      $(\'.box-body\').has(eDom).append(divProcessBar);\r\n            $.ajax({\r\n   " +
"             type: \"POST\",\r\n                url: \"/XLHSDangKy/DanhSachChu_ChiTie" +
"tChu\",\r\n                data: { dangKyNguoiID: rowData.DANGKYNGUOIID },\r\n       " +
"         dataType: \"html\",\r\n                success: function (html) {\r\n        " +
"            $(\'#DangKyTableChuID_wrapper\').addClass(\"d-none\");\r\n                " +
"    $(\'.box-body\').has(\'#DangKyTableChuID_wrapper\').append(html);\r\n             " +
"   },\r\n                error: function (jqXHR, textStatus, errorThrown) {\r\n     " +
"               alert(\'Lỗi: \' + errorThrown);\r\n                },\r\n              " +
"  complete: function () {\r\n                    $(\'.overlay\', $(\'.box-body\').has(" +
"eDom)).remove();\r\n                }\r\n            })\r\n        }\r\n\r\n        $(\'#bt" +
"nThemChuID\').on(\'click\', function () {\r\n            var eDom = $(this);\r\n       " +
"     $(\'.box-body\').has($(this)).append(divProcessBar);\r\n            $.ajax({\r\n " +
"               type: \"POST\",\r\n                url: \"/XLHSDangKy/DanhSachChu_Them" +
"MoiChu\",\r\n                data: { loaiChuID: $(\'#CBLOAICHUID\').val() },\r\n       " +
"         dataType: \"html\",\r\n                success: function (html) {\r\n        " +
"            $(\'#DangKyTableChuID_wrapper\').addClass(\"d-none\");\r\n                " +
"    $(\'.box-body\').has(\'#DangKyTableChuID_wrapper\').append(html);\r\n             " +
"   },\r\n                error: function (jqXHR, textStatus, errorThrown) {\r\n     " +
"               alert(\'Lỗi: \' + errorThrown);\r\n                },\r\n              " +
"  complete: function () {\r\n                    $(\'.overlay\', $(\'.box-body\').has(" +
"eDom)).remove();\r\n                }\r\n            })\r\n        })\r\n\r\n        funct" +
"ion XoaChuKhoiDangKy(table, rowData, rowDel) {\r\n            if (confirm(\"Xác nhậ" +
"n xóa chủ khỏi đăng ký?\")) {\r\n                var dangKyNguoiID = rowData.DANGKY" +
"NGUOIID;\r\n                $.ajax({\r\n                    type: \"POST\",\r\n         " +
"           url: \"/XLHSDangKy/DanhSachChu_XoaChu\",\r\n                    data: { d" +
"angKyNguoiID: dangKyNguoiID },\r\n                    dataType: \"json\",\r\n         " +
"           success: function (result) {\r\n                        if (result.succ" +
"ess) {\r\n                            table\r\n                            .row(rowD" +
"el)\r\n                            .remove();\r\n                            //Cập n" +
"hật lại STT cho dataTable\r\n                            var i = 1;\r\n             " +
"               table.rows().every(function () {\r\n                               " +
" var d = this.data();\r\n                                d.STT = i++;\r\n           " +
"                     d.STT += \".\";\r\n                                table.row(th" +
"is).data(d);\r\n                            })\r\n                            //Vẽ l" +
"ại dataTable sau khi cập nhật\r\n                            table.draw();\r\n      " +
"                  }\r\n                        alert(result.mes);\r\n               " +
"     }\r\n                })\r\n            }\r\n        }\r\n\r\n        $(\'#CBLOAICHUID\'" +
").appendTo(\'#CMLOAICHUID\');\r\n\r\n    })\r\n</script>\r\n");

        }
    }
}
#pragma warning restore 1591
