#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MPLIS;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/XLHSDangKy/lstNhaChungCu.cshtml")]
    public partial class _Views_XLHSDangKy_lstNhaChungCu_cshtml : System.Web.Mvc.WebViewPage<AppCore.Models.DangKyTaiSan>
    {
        public _Views_XLHSDangKy_lstNhaChungCu_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\XLHSDangKy\lstNhaChungCu.cshtml"
Write(Html.HiddenFor(m => m.CurNhaChungCu.NHACHUNGCUID, new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 3 "..\..\Views\XLHSDangKy\lstNhaChungCu.cshtml"
Write(Html.HiddenFor(m => m.CurNhaChungCu.uId, new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n<table");

WriteLiteral(" id=\"table_NHACHUNGCU\"");

WriteLiteral(" class=\"table table-bordered\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n            <th");

WriteLiteral(" class=\"t100\"");

WriteLiteral(" hidden>TAISAN _ID</th>\r\n            <th");

WriteLiteral(" class=\"t50\"");

WriteLiteral(">STT</th>\r\n            <th");

WriteLiteral(" class=\"t100\"");

WriteLiteral(">Tên Nhà</th>\r\n            <th");

WriteLiteral(" class=\"t100\"");

WriteLiteral(">Diện tích</th>\r\n        </tr>\r\n    </thead>\r\n    <tbody>\r\n");

            
            #line 14 "..\..\Views\XLHSDangKy\lstNhaChungCu.cshtml"
        
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\XLHSDangKy\lstNhaChungCu.cshtml"
          
            int rtdtable = 0;
            if (Model != null)
            {
                if (Model.lstNhaChungCu != null)
                {
                    foreach (var item in Model.lstNhaChungCu)
                    {
                        rtdtable = rtdtable + 1;

            
            #line default
            #line hidden
WriteLiteral("                        <tr");

WriteLiteral(" data-id=\"");

            
            #line 23 "..\..\Views\XLHSDangKy\lstNhaChungCu.cshtml"
                                Write(item.NHACHUNGCUID);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                            <td");

WriteLiteral(" align=\"center\"");

WriteLiteral(" hidden>");

            
            #line 24 "..\..\Views\XLHSDangKy\lstNhaChungCu.cshtml"
                                                 Write(item.uId);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td");

WriteLiteral(" align=\"center\"");

WriteLiteral(">");

            
            #line 25 "..\..\Views\XLHSDangKy\lstNhaChungCu.cshtml"
                                          Write(rtdtable);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td");

WriteLiteral(" align=\"center\"");

WriteLiteral(">");

            
            #line 26 "..\..\Views\XLHSDangKy\lstNhaChungCu.cshtml"
                                          Write(item.TENCHUNGCU);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td");

WriteLiteral(" align=\"center\"");

WriteLiteral(">");

            
            #line 27 "..\..\Views\XLHSDangKy\lstNhaChungCu.cshtml"
                                          Write(item.DIENTICHSAN);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        </tr>\r\n");

            
            #line 29 "..\..\Views\XLHSDangKy\lstNhaChungCu.cshtml"

                    }
                }
            }
        
            
            #line default
            #line hidden
WriteLiteral("\r\n    </tbody>\r\n</table>\r\n<script>\r\n    $(document).ready(function () {\r\n        " +
"InitDataTableXLHS($(\'#table_NHACHUNGCU\'));\r\n    });\r\n    function removeRowncc(b" +
"utton) {\r\n        var ans = confirm(\"Bạn chắc chắn muốn xóa?\");\r\n        //" +
"=== If user pressed Ok then delete the record else do nothing.\r\n        if (ans " +
"== true) {\r\n            //alert(\'xóa thành công!\');\r\n            var empTab = " +
"document.getElementById(\'table_NHACHUNGCU\');\r\n            var index = button.par" +
"entNode.parentNode.rowIndex;\r\n            // alert(index);\r\n            var tais" +
"anid = empTab.rows[index].cells[0].innerHTML;\r\n            var dondk = $(\'#DONDA" +
"NGKYID\').val();\r\n            empTab.deleteRow(button.parentNode.parentNode.rowIn" +
"dex);\r\n                $.ajax({\r\n                    type: \"POST\",\r\n            " +
"        url: \"/XLHSDangKy/XOA_NHACHUNGCU\",\r\n                    dataType: \"json\"" +
",\r\n                    contentType: \"application/json\",\r\n                    dat" +
"a: JSON.stringify({ nhaid: taisanid.trim(), dondangky_id: dondk.trim() }),\r\n    " +
"                success: function (data) {\r\n                        if (data ===" +
" \"true\") {\r\n                            alert(\"Xóa thành công!\");\r\n           " +
"             }\r\n                        else {\r\n                            aler" +
"t(\"Có lỗi xảy ra!\");\r\n                        }\r\n                    },\r\n    " +
"            });\r\n            }\r\n\r\n\r\n        \r\n    }\r\n    $(function () {\r\n      " +
"  $(\"#table_NHACHUNGCU tbody\").on(\"click\", \"tr\", function (e) {\r\n            $(t" +
"his).addClass(\'activerow\').siblings().removeClass(\'activerow\');\r\n            var" +
" taisanid = $(this)[0].cells[0].innerHTML;\r\n            var dondk = $(\'#DONDANGK" +
"YID\').val();\r\n            $.ajax({\r\n                type: \"POST\",\r\n             " +
"   url: \"/XLHSDangKy/ChiTietNhaChungCu\",\r\n                data: { idtaisan: tais" +
"anid.trim(), Loaitaisan: \"3\" },\r\n                datatype: \"html\",\r\n            " +
"    success: function (data) {\r\n                    $(\'#tabNhaChungCu\').html(dat" +
"a);\r\n                }\r\n            });\r\n        });\r\n\r\n    });\r\n</script>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
