#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\XLHSDangKy\Popup_DiaChiTaiSan.cshtml"
    using AppCore.Models;
    
    #line default
    #line hidden
    using MPLIS;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/XLHSDangKy/Popup_DiaChiTaiSan.cshtml")]
    public partial class _Views_XLHSDangKy_Popup_DiaChiTaiSan_cshtml : System.Web.Mvc.WebViewPage<AppCore.Models.DC_DIACHI>
    {
        public _Views_XLHSDangKy_Popup_DiaChiTaiSan_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\'modal fade\'");

WriteLiteral(" id=\'modalformDiaChi\'");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\'modal-dialog\'");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\'modal-content\'");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\'modal-header\'");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\'button\'");

WriteLiteral(" class=\'close\'");

WriteLiteral(" data-dismiss=\'modal\'");

WriteLiteral(">&times;</button>\r\n                <h4");

WriteLiteral(" class=\'modal-title\'");

WriteLiteral(" id=\"title_popup_diachi\"");

WriteLiteral(">Địa chỉ</h4>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\'modal-body\'");

WriteLiteral(" id=\"modalformDiaChi_body\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 11 "..\..\Views\XLHSDangKy\Popup_DiaChiTaiSan.cshtml"
           Write(Html.Partial("_ChiTietDiaChi"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\'modal-footer\'");

WriteLiteral(" style=\'text-align:center;\'");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\'submit\'");

WriteLiteral(" id=\"btnthemdiachi\"");

WriteLiteral(" class=\'t100 btn btn-primary btn-sm pull-right\'");

WriteLiteral(">Lưu</button>\r\n                <button");

WriteLiteral(" type=\'submit\'");

WriteLiteral(" id=\"btnlammoidiachi\"");

WriteLiteral(" class=\'t100 btn btn-primary btn-sm pull-left\'");

WriteLiteral(">Làm mới</button>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n<scrip" +
"t>\r\n    $(document).ready(function () {\r\n        $(\'#btnthemdiachi\').on(\"click\"," +
" function () {\r\n            $(\'#drpxa\').prop(\"disabled\", false);\r\n            $(" +
"\'#drphuyen\').prop(\"disabled\", false);\r\n            var formdata = $(\'#pop_up_the" +
"mdiachi\').serializeArray();\r\n            $.ajax({\r\n                type: \"POST\"," +
"\r\n                url: \"/XLHSDangKy/ThemDiaChi\",\r\n                data: formdata" +
",\r\n                success: function (data) {\r\n                    if ($(\"#drpch" +
"ontaisan\").val() == \"1\") {\r\n                        $(\'#CurNhaRiengLe_DIACHI\').h" +
"tml(data);\r\n                    }\r\n                    else if ($(\"#drpchontaisa" +
"n\").val() == \"4\") {\r\n                    }\r\n                    else if ($(\"#drp" +
"chontaisan\").val() == \"6\") {\r\n                        $(\'#CurCongTrinhXayDung_DI" +
"ACHI\').html(data);\r\n                    }\r\n                    else if ($(\"#drpc" +
"hontaisan\").val() == \"7\") {\r\n                        $(\'#CurCongTrinhNgam_DIACHI" +
"\').html(data);\r\n                    }\r\n                    else if ($(\"#drpchont" +
"aisan\").val() == \"8\") {\r\n                        $(\'#CurHangMucCongTrinh_DIACHII" +
"D\').html(data);\r\n                    }\r\n                    else if ($(\"#drpchon" +
"taisan\").val() == \"9\") {\r\n                        $(\'#CurRungTrong_DIACHI\').html" +
"(data);\r\n                    }\r\n                    else if ($(\"#drpchontaisan\")" +
".val() == \"10\") {\r\n                        $(\'#CurCayLauNam_DIACHI\').html(data);" +
"\r\n                    }\r\n                }\r\n            });\r\n        });\r\n      " +
"  $(\'#btnlammoidiachi\').on(\"click\", function () {\r\n            $.ajax({\r\n       " +
"         type: \"GET\",\r\n                url: \"/XLHSDangKy/LoadDiaChi\",\r\n         " +
"       success: function (html) {\r\n                    $(\'#modalformDiaChi_body\'" +
").html(html);\r\n                }\r\n            });\r\n        });\r\n    });\r\n</scrip" +
"t>");

        }
    }
}
#pragma warning restore 1591
