#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MPLIS;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/XLHSDangKyV2/_DonDangKy_DSChu.cshtml")]
    public partial class _Views_XLHSDangKyV2__DonDangKy_DSChu_cshtml : System.Web.Mvc.WebViewPage<MPLIS.Libraries.Data.XuLyHoSo.Models.DSChuDonVM>
    {
        public _Views_XLHSDangKyV2__DonDangKy_DSChu_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"box box-primary\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"box-header p-0\"");

WriteLiteral("></div>\r\n    <div");

WriteLiteral(" id=\"divBoxBodyDSDangKyChuID\"");

WriteLiteral(" class=\"box-body\"");

WriteLiteral(" style=\"padding-bottom:5px;\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" id=\"tableDangKyChuID\"");

WriteLiteral(" class=\"table table-bordered\"");

WriteLiteral(@">
            <thead>
                <tr>
                    <th></th>
                    <th></th>
                    <th>#</th>
                    <th>Loại chủ</th>
                    <th>Tên chủ</th>
                    <th>CMT/Hộ chiếu</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
");

            
            #line 19 "..\..\Views\XLHSDangKyV2\_DonDangKy_DSChu.cshtml"
                
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\XLHSDangKyV2\_DonDangKy_DSChu.cshtml"
                 if (Model.DSDangKyChu != null && Model.DSDangKyChu.Count > 0)
                {
                    int sTT = 0;
                    foreach (var item in Model.DSDangKyChu)
                    {
                        sTT++;

            
            #line default
            #line hidden
WriteLiteral("                        <tr>\r\n                            <td>\r\n");

WriteLiteral("                                ");

            
            #line 27 "..\..\Views\XLHSDangKyV2\_DonDangKy_DSChu.cshtml"
                           Write(item.LOAI);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                            <td>\r\n");

WriteLiteral("                                ");

            
            #line 30 "..\..\Views\XLHSDangKyV2\_DonDangKy_DSChu.cshtml"
                           Write(item.DANGKYNGUOIID);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                            <td>\r\n");

WriteLiteral("                                ");

            
            #line 33 "..\..\Views\XLHSDangKyV2\_DonDangKy_DSChu.cshtml"
                           Write(sTT);

            
            #line default
            #line hidden
WriteLiteral(".\r\n                            </td>\r\n                            <td>\r\n");

WriteLiteral("                                ");

            
            #line 36 "..\..\Views\XLHSDangKyV2\_DonDangKy_DSChu.cshtml"
                           Write(item.Chu_TenLoaiChu);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                            <td>\r\n");

WriteLiteral("                                ");

            
            #line 39 "..\..\Views\XLHSDangKyV2\_DonDangKy_DSChu.cshtml"
                           Write(item.Chu_HoTen);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                            <td>\r\n");

WriteLiteral("                                ");

            
            #line 42 "..\..\Views\XLHSDangKyV2\_DonDangKy_DSChu.cshtml"
                           Write(item.Chu_CMT);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                            <td></td>\r\n     " +
"                   </tr>\r\n");

            
            #line 46 "..\..\Views\XLHSDangKyV2\_DonDangKy_DSChu.cshtml"
                    }
                }

            
            #line default
            #line hidden
WriteLiteral("            </tbody>\r\n        </table>\r\n    </div>\r\n    <button");

WriteLiteral(" id=\"btnThem_tableDangKyChuID\"");

WriteLiteral(" class=\"btn btn-sm btn-default\"");

WriteLiteral("><i");

WriteLiteral(" class=\'fa fa-plus\'");

WriteLiteral("></i> Thêm mới</button>\r\n");

WriteLiteral("    ");

            
            #line 52 "..\..\Views\XLHSDangKyV2\_DonDangKy_DSChu.cshtml"
Write(Html.DropDownList("LoaiChuID", new SelectList(ViewBag.dSLoaiChu, "LOAICHUID", "TENLOAICHU"), "---- Chọn loại chủ ----", new { @class = "form-control input-sm", @id = "comboBox_LoaiChuID" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    $(document).ready(function () {\r\n\r\n        var divProcessBar = \"<div class" +
"=\'overlay\'> <i class=\'fa fa-refresh fa-spin\'></i> </div>\";\r\n\r\n        var column" +
"s = [\r\n            { \"data\": \"LOAI\" },\r\n            { \"data\": \"DANGKYNGUOIID\" }," +
"\r\n            { \"data\": \"STT\" },\r\n            { \"data\": \"TENLOAICHU\" },\r\n       " +
"     { \"data\": \"TENCHU\" },\r\n            { \"data\": \"CMT\" },\r\n            { \"data\"" +
": null }\r\n        ]\r\n\r\n        var columnDefs = [\r\n            {\r\n              " +
"  \"targets\": [0, 1],\r\n                \"visible\": false\r\n            },\r\n        " +
"    {\r\n                \"targets\": -1,\r\n                \"render\": function () {\r\n" +
"                    return \"<button type=\'button\' class=\'btn btn-xs btn-heading " +
"btnDel\'>Xóa</button>\";\r\n                }\r\n            },\r\n            {\r\n      " +
"          \"targets\": 2,\r\n                \"className\": \"text-right\"\r\n            " +
"},\r\n            {\r\n                \"targets\": -1,\r\n                \"className\": " +
"\"text-center\"\r\n            }\r\n        ]\r\n\r\n        var options = {\r\n            " +
"\"pageLength\": 5,\r\n            \"ordering\": false,\r\n            \"autoWidth\": false" +
",\r\n            \"columns\": columns,\r\n            \"columnDefs\": columnDefs,\r\n     " +
"       \"dom\": \"t<\'row p-0\'<\'col-xs-6 p-0\'<\'row p-0\'<\'col-xs-6 p-0\'<\'#divComboBox" +
"_tableDangKyChuID\'>><\'col-xs-6 p-0\' <\'#divButton_tableDangKyChuID\'>>>><\'col-xs-6" +
" p-0\'<\'pull-right\'p>>>\",\r\n            \"initComplete\": function () {\r\n           " +
"     initComplete();\r\n            }\r\n        }\r\n\r\n        function initComplete(" +
") {\r\n            $(\'#btnThem_tableDangKyChuID\').appendTo($(\'#divButton_tableDang" +
"KyChuID\'));\r\n            $(\'#comboBox_LoaiChuID\').appendTo($(\'#divComboBox_table" +
"DangKyChuID\'));\r\n        }\r\n\r\n        var tableDangKyChuID = $(\'#tableDangKyChuI" +
"D\').DataTable(options);\r\n\r\n        tableDangKyChuID.rows().nodes().on(\'dblclick\'" +
", \'tbody tr\', function () {\r\n            if (tableDangKyChuID.rows().nodes().len" +
"gth > 0) {\r\n                var rowData = tableDangKyChuID.row($(this)).data();\r" +
"\n                $(\'#divBoxBodyDSDangKyChuID\').append(divProcessBar);\r\n         " +
"       $.ajax({\r\n                    type: \"POST\",\r\n                    url: \"/X" +
"LHSDangKyV2/_DanhSachChu_ChiTietChu\",\r\n                    data: { dangKyNguoiID" +
": rowData.DANGKYNGUOIID },\r\n                    success: function (result) {\r\n  " +
"                      if (result.message == undefined) {\r\n                      " +
"      $(\'#tableDangKyChuID_wrapper\').addClass(\"d-none\");\r\n                      " +
"      $(\'#divBoxBodyDSDangKyChuID\').append(result);\r\n                        } e" +
"lse {\r\n                            alert(result.message);\r\n                     " +
"   }\r\n                    },\r\n                    error: function (jqXHR, textSt" +
"atus, errorThrown) {\r\n                        alert(\'Lỗi: \' + errorThrown);\r\n   " +
"                 },\r\n                    complete: function () {\r\n              " +
"          $(\'.overlay\', $(\'#divBoxBodyDSDangKyChuID\')).remove();\r\n              " +
"      }\r\n                })\r\n            }\r\n        })\r\n\r\n        tableDangKyChu" +
"ID.rows().nodes().on(\'click\', \'tbody tr button\', function (event) {\r\n           " +
" event.stopPropagation();\r\n        })\r\n\r\n        tableDangKyChuID.rows().nodes()" +
".on(\'click\', \'tbody tr .btnDel\', function (event) {\r\n            var rowData = t" +
"ableDangKyChuID.row($(this).parents(\'tr\')).data();\r\n            if (confirm(\"Xác" +
" nhận xóa chủ trong đăng ký?\")) {\r\n                $.ajax({\r\n                   " +
" type: \"POST\",\r\n                    url: \"/XLHSDangKyV2/DanhSachChu_XoaChu\",\r\n  " +
"                  data: { dangKyNguoiID: rowData.DANGKYNGUOIID },\r\n             " +
"       dataType: \"json\",\r\n                    success: function (result) {\r\n    " +
"                    if (result.success) {\r\n\r\n                        }\r\n        " +
"                alert(result.message);\r\n                    }\r\n                }" +
")\r\n            }\r\n        })\r\n\r\n        $(\'#btnThem_tableDangKyChuID\').on(\'click" +
"\', function () {\r\n            $(\'#divBoxBodyDSDangKyChuID\').append(divProcessBar" +
");\r\n            $.ajax({\r\n                type: \"POST\",\r\n                url: \"/" +
"XLHSDangKyV2/DanhSachChu_ThemMoiChu\",\r\n                data: { loaiChuID: $(\'#CB" +
"LOAICHUID\').val() },\r\n                dataType: \"html\",\r\n                success" +
": function (html) {\r\n                    $(\'#tableDangKyChuID_wrapper\').addClass" +
"(\"d-none\");\r\n                    $(\'#divBoxBodyDSDangKyChuID\').append(html);\r\n  " +
"              },\r\n                error: function (jqXHR, textStatus, errorThrow" +
"n) {\r\n                    alert(\'Lỗi: \' + errorThrown);\r\n                },\r\n   " +
"             complete: function () {\r\n                    $(\'.overlay\', $(\'#divB" +
"oxBodyDSDangKyChuID\')).remove();\r\n                }\r\n            })\r\n        })\r" +
"\n\r\n    })\r\n</script>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
