#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class _Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {

#line 125 "..\..\Views\Home\Index.cshtml"
public System.Web.WebPages.HelperResult SuaTenUngDung(string LinkUngDung, string KiemTraUngDung, string ThuTuUngDung, string TenUngDung, string MauNen)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 126 "..\..\Views\Home\Index.cshtml"
 
string chuoi = TenUngDung.Trim();
string dong1 = "";
string chuoiMoi = "";
int i = 1;
while (chuoi.IndexOf(" ") >= 0)
{
    dong1 = dong1 + " " + chuoi.Substring(0, chuoi.IndexOf(" "));
    chuoi = chuoi.Substring(chuoi.IndexOf(" ")).Trim();
    i = i + 1;
    if (i > 4)
    {
        break;
    }
}
if (i > 4)
{
    chuoiMoi = dong1.Trim() + "<br/>" + chuoi;


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <a");

WriteAttributeTo(__razor_helper_writer, "href", Tuple.Create(" href=\"", 13134), Tuple.Create("\"", 13153)

#line 144 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 13141), Tuple.Create<System.Object, System.Int32>(LinkUngDung

#line default
#line hidden
, 13141), false)
);

WriteAttributeTo(__razor_helper_writer, "onclick", Tuple.Create(" onclick=\"", 13154), Tuple.Create("\"", 13214)
, Tuple.Create(Tuple.Create("", 13164), Tuple.Create("KiemTraUngDung(\'", 13164), true)

#line 144 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 13180), Tuple.Create<System.Object, System.Int32>(KiemTraUngDung

#line default
#line hidden
, 13180), false)
, Tuple.Create(Tuple.Create("", 13195), Tuple.Create("\',\'", 13195), true)

#line 144 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 13198), Tuple.Create<System.Object, System.Int32>(ThuTuUngDung

#line default
#line hidden
, 13198), false)
, Tuple.Create(Tuple.Create("", 13211), Tuple.Create("\');", 13211), true)
);

WriteLiteralTo(__razor_helper_writer, " class=\"btn btn-microsoft btn-lg\"");

WriteAttributeTo(__razor_helper_writer, "style", Tuple.Create(" style=\"", 13248), Tuple.Create("\"", 13369)
, Tuple.Create(Tuple.Create("", 13256), Tuple.Create("width:180px;", 13256), true)
, Tuple.Create(Tuple.Create(" ", 13268), Tuple.Create("height:", 13269), true)
, Tuple.Create(Tuple.Create(" ", 13276), Tuple.Create("60px;", 13277), true)
, Tuple.Create(Tuple.Create(" ", 13282), Tuple.Create("padding-top:5px;", 13283), true)
, Tuple.Create(Tuple.Create(" ", 13299), Tuple.Create("font-family:\'Times", 13300), true)
, Tuple.Create(Tuple.Create(" ", 13318), Tuple.Create("New", 13319), true)
, Tuple.Create(Tuple.Create(" ", 13322), Tuple.Create("Roman\',", 13323), true)
, Tuple.Create(Tuple.Create(" ", 13330), Tuple.Create("Times,", 13331), true)
, Tuple.Create(Tuple.Create(" ", 13337), Tuple.Create("serif;background-color:", 13338), true)

#line 144 "..\..\Views\Home\Index.cshtml"
                                                                                                                                                            , Tuple.Create(Tuple.Create("", 13361), Tuple.Create<System.Object, System.Int32>(MauNen

#line default
#line hidden
, 13361), false)
, Tuple.Create(Tuple.Create("", 13368), Tuple.Create(";", 13368), true)
);

WriteLiteralTo(__razor_helper_writer, ">");


#line 144 "..\..\Views\Home\Index.cshtml"
                                                                                                                                                                                                                         WriteTo(__razor_helper_writer, Html.Raw(chuoiMoi));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</a>\r\n");


#line 145 "..\..\Views\Home\Index.cshtml"
}
else
{
    chuoiMoi = dong1.Trim() + " " + chuoi;


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <a");

WriteAttributeTo(__razor_helper_writer, "href", Tuple.Create(" href=\"", 13462), Tuple.Create("\"", 13481)

#line 149 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 13469), Tuple.Create<System.Object, System.Int32>(LinkUngDung

#line default
#line hidden
, 13469), false)
);

WriteAttributeTo(__razor_helper_writer, "onclick", Tuple.Create(" onclick=\"", 13482), Tuple.Create("\"", 13542)
, Tuple.Create(Tuple.Create("", 13492), Tuple.Create("KiemTraUngDung(\'", 13492), true)

#line 149 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 13508), Tuple.Create<System.Object, System.Int32>(KiemTraUngDung

#line default
#line hidden
, 13508), false)
, Tuple.Create(Tuple.Create("", 13523), Tuple.Create("\',\'", 13523), true)

#line 149 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 13526), Tuple.Create<System.Object, System.Int32>(ThuTuUngDung

#line default
#line hidden
, 13526), false)
, Tuple.Create(Tuple.Create("", 13539), Tuple.Create("\');", 13539), true)
);

WriteLiteralTo(__razor_helper_writer, " class=\"btn btn-microsoft btn-lg\"");

WriteAttributeTo(__razor_helper_writer, "style", Tuple.Create(" style=\"", 13576), Tuple.Create("\"", 13698)
, Tuple.Create(Tuple.Create("", 13584), Tuple.Create("width:180px;", 13584), true)
, Tuple.Create(Tuple.Create(" ", 13596), Tuple.Create("height:", 13597), true)
, Tuple.Create(Tuple.Create(" ", 13604), Tuple.Create("60px;", 13605), true)
, Tuple.Create(Tuple.Create(" ", 13610), Tuple.Create("padding-top:15px;", 13611), true)
, Tuple.Create(Tuple.Create(" ", 13628), Tuple.Create("font-family:\'Times", 13629), true)
, Tuple.Create(Tuple.Create(" ", 13647), Tuple.Create("New", 13648), true)
, Tuple.Create(Tuple.Create(" ", 13651), Tuple.Create("Roman\',", 13652), true)
, Tuple.Create(Tuple.Create(" ", 13659), Tuple.Create("Times,", 13660), true)
, Tuple.Create(Tuple.Create(" ", 13666), Tuple.Create("serif;background-color:", 13667), true)

#line 149 "..\..\Views\Home\Index.cshtml"
                                                                                                                                                             , Tuple.Create(Tuple.Create("", 13690), Tuple.Create<System.Object, System.Int32>(MauNen

#line default
#line hidden
, 13690), false)
, Tuple.Create(Tuple.Create("", 13697), Tuple.Create(";", 13697), true)
);

WriteLiteralTo(__razor_helper_writer, ">");


#line 149 "..\..\Views\Home\Index.cshtml"
                                                                                                                                                                                                                          WriteTo(__razor_helper_writer, Html.Raw(chuoiMoi));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</a>\r\n");


#line 150 "..\..\Views\Home\Index.cshtml"
}


#line default
#line hidden
});

#line 151 "..\..\Views\Home\Index.cshtml"
}
#line default
#line hidden

        public _Views_Home_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Đăng nhập hệ thống";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!-- Full Width Column -->\r\n<div");

WriteLiteral(" class=\"wrapper\"");

WriteLiteral(">\r\n    <header");

WriteLiteral(" class=\"main-header\"");

WriteLiteral(" style=\"background-color: #00a65a;\"");

WriteLiteral(">\r\n        ");

WriteLiteral("\r\n        ");

WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <nav");

WriteLiteral(" class=\"navbar navbar-static-top\"");

WriteLiteral(" style=\"margin-left: 0px;\"");

WriteLiteral(">\r\n                ");

WriteLiteral("\r\n                <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"navbar-brand\"");

WriteLiteral(" style=\"padding-left:0px;padding-right:4px;\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 670), Tuple.Create("\"", 697)
, Tuple.Create(Tuple.Create("", 676), Tuple.Create<System.Object, System.Int32>(Href("~/Images/Picture1.png")
, 676), false)
);

WriteLiteral(" width=\"38\"");

WriteLiteral(" height=\"30\"");

WriteLiteral(" /></div>\r\n                    <div");

WriteLiteral(" class=\"navbar-brand\"");

WriteLiteral(" style=\"font-family:\'Times New Roman\', Times, serif;padding-left:4px;padding-righ" +
"t:4px;font-size:20px;\"");

WriteLiteral("><b>Hệ thống thông tin đất đai quốc gia đa mục tiêu - MPLIS</b></div>\r\n          " +
"      </div>\r\n                ");

WriteLiteral("\r\n            </nav>\r\n        </div>\r\n</header>\r\n    <div");

WriteLiteral(" class=\"content-wrapper\"");

WriteLiteral(">\r\n        <!-- Content Header (Page header) -->\r\n        <!-- Main content -->\r\n" +
"        <!--Main Layout-->\r\n        <br />\r\n        <section");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" style=\"padding-top: 16px; padding-left:230px;\"");

WriteLiteral(">\r\n                ");

WriteLiteral("\r\n                <fieldset");

WriteLiteral(" style=\"padding-left:310px;\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n                    <div>\r\n                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1531), Tuple.Create("\"", 1558)
            
            #line 33 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1537), Tuple.Create<System.Object, System.Int32>(ViewBag.AnhBieuTuong
            
            #line default
            #line hidden
, 1537), false)
);

WriteLiteral(" alt=\"Chưa có ảnh đại diện !\"");

WriteLiteral(" class=\"img-circle\"");

WriteLiteral(" width=\"104\"");

WriteLiteral(" height=\"100\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" data-target=\"#ThongTinCaNhan\"");

WriteLiteral(" />\r\n                    </div>\r\n                    <br />\r\n                </fi" +
"eldset>\r\n                <fieldset");

WriteLiteral(" style=\"font-size:19px;padding-left:200px; font-size:18px;\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n                    <u><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" style=\"text-align:center; font-family:\'Times New Roman\', Times, serif\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" data-target=\"#ThongTinCaNhan\"");

WriteLiteral(">");

            
            #line 39 "..\..\Views\Home\Index.cshtml"
                                                                                                                                                       Write(ViewBag.tenguoidung);

            
            #line default
            #line hidden
WriteLiteral("</a></u>\r\n                    &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;" +
" &nbsp;\r\n                    <u><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2208), Tuple.Create("\"", 2228)
, Tuple.Create(Tuple.Create("", 2215), Tuple.Create<System.Object, System.Int32>(Href("~/Home/Logout")
, 2215), false)
);

WriteLiteral(" style=\"font-family:\'Times New Roman\', Times, serif\"");

WriteLiteral(">Đăng xuất</a></u>\r\n                    <br />\r\n                    <br />\r\n     " +
"               ");

WriteLiteral("\r\n                </fieldset>\r\n                <fieldset");

WriteLiteral(" style=\"font-size:9px;\"");

WriteLiteral(">\r\n                    <!--Hàng ứng dụng thứ 1-->\r\n                    <!--Ô úng " +
"dung thứ 1-->\r\n                    ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 50 "..\..\Views\Home\Index.cshtml"
               Write(SuaTenUngDung((string)ViewData["LinkUngDung11"], (string)ViewData["KiemTraUngDung11"], (string)ViewData["ThuTuUngDung11"], (string)ViewData["TenUngDung11"], "#3C8DBC"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <!--Ô úng dung thứ 2-->\r\n                    ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 53 "..\..\Views\Home\Index.cshtml"
               Write(SuaTenUngDung((string)ViewData["LinkUngDung12"], (string)ViewData["KiemTraUngDung12"], (string)ViewData["ThuTuUngDung12"], (string)ViewData["TenUngDung12"], "#449C44"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    ");

WriteLiteral("\r\n                    <!--Ô úng dung thứ 3-->\r\n                    ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 57 "..\..\Views\Home\Index.cshtml"
               Write(SuaTenUngDung((string)ViewData["LinkUngDung13"], (string)ViewData["KiemTraUngDung13"], (string)ViewData["ThuTuUngDung13"], (string)ViewData["TenUngDung13"], "#3C8DBC"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <!--Ô úng dung thứ 4-->\r\n                    ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 60 "..\..\Views\Home\Index.cshtml"
               Write(SuaTenUngDung((string)ViewData["LinkUngDung14"], (string)ViewData["KiemTraUngDung14"], (string)ViewData["ThuTuUngDung14"], (string)ViewData["TenUngDung14"], "#449C44"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <br />\r\n                    <br />\r\n                    <!-" +
"-Hàng ứng dụng thứ 2-->\r\n                    <!--Ô úng dung thứ 1-->\r\n          " +
"          ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 66 "..\..\Views\Home\Index.cshtml"
               Write(SuaTenUngDung((string)ViewData["LinkUngDung21"], (string)ViewData["KiemTraUngDung21"], (string)ViewData["ThuTuUngDung21"], (string)ViewData["TenUngDung21"], "#449C44"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    ");

WriteLiteral("\r\n                    <!--Ô úng dung thứ 2-->\r\n                    ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 70 "..\..\Views\Home\Index.cshtml"
               Write(SuaTenUngDung((string)ViewData["LinkUngDung22"], (string)ViewData["KiemTraUngDung22"], (string)ViewData["ThuTuUngDung22"], (string)ViewData["TenUngDung22"], "#3C8DBC"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    ");

WriteLiteral("\r\n                    <!--Ô úng dung thứ 3-->\r\n                    ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 74 "..\..\Views\Home\Index.cshtml"
               Write(SuaTenUngDung((string)ViewData["LinkUngDung23"], (string)ViewData["KiemTraUngDung23"], (string)ViewData["ThuTuUngDung23"], (string)ViewData["TenUngDung23"], "#449C44"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <!--Ô úng dung thứ 4-->\r\n                    ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 77 "..\..\Views\Home\Index.cshtml"
               Write(SuaTenUngDung((string)ViewData["LinkUngDung24"], (string)ViewData["KiemTraUngDung24"], (string)ViewData["ThuTuUngDung24"], (string)ViewData["TenUngDung24"], "#3C8DBC"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <br />\r\n                    <br />\r\n                    <!-" +
"-Hàng ứng dụng thứ 2-->\r\n                    <!--Ô úng dung thứ 1-->\r\n          " +
"          ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 83 "..\..\Views\Home\Index.cshtml"
               Write(SuaTenUngDung((string)ViewData["LinkUngDung31"], (string)ViewData["KiemTraUngDung31"], (string)ViewData["ThuTuUngDung31"], (string)ViewData["TenUngDung31"], "#3C8DBC"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <!--Ô úng dung thứ 2-->\r\n                    ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 86 "..\..\Views\Home\Index.cshtml"
               Write(SuaTenUngDung((string)ViewData["LinkUngDung32"], (string)ViewData["KiemTraUngDung32"], (string)ViewData["ThuTuUngDung32"], (string)ViewData["TenUngDung32"], "#449C44"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    ");

WriteLiteral("\r\n                    <!--Ô úng dung thứ 3-->\r\n                    ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 90 "..\..\Views\Home\Index.cshtml"
               Write(SuaTenUngDung((string)ViewData["LinkUngDung33"], (string)ViewData["KiemTraUngDung33"], (string)ViewData["ThuTuUngDung33"], (string)ViewData["TenUngDung33"], "#3C8DBC"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <!--Ô úng dung thứ 4-->\r\n                    ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 93 "..\..\Views\Home\Index.cshtml"
               Write(SuaTenUngDung((string)ViewData["LinkUngDung34"], (string)ViewData["KiemTraUngDung34"], (string)ViewData["ThuTuUngDung34"], (string)ViewData["TenUngDung34"], "#449C44"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <br />\r\n                    <br /> ");

WriteLiteral("\r\n                    ");

WriteLiteral("\r\n                    ");

WriteLiteral("\r\n                    ");

WriteLiteral("\r\n                    ");

WriteLiteral("\r\n                    ");

WriteLiteral("\r\n                </fieldset>\r\n            </div>\r\n        </section>\r\n        <!" +
"--/EndMainLayout-->\r\n        <!-- /.content -->\r\n    </div>\r\n    <!-- /.containe" +
"r -->\r\n    <!-- /.content-wrapper -->\r\n    <footer");

WriteLiteral(" class=\"main-footer\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(" style=\"font-family:\'Times New Roman\', Times, serif\"");

WriteLiteral(">\r\n            <strong>Bản quyền thuộc về FPT và Tổng cục Quản lý đất đai - Bộ Tà" +
"i nguyên và Môi trường</strong>\r\n        </div>\r\n        <!-- /.container -->\r\n " +
"   </footer>\r\n</div>\r\n\r\n<!-- ./wrapper -->\r\n<!--Popup Thông tin cá nhân-->\r\n<div" +
"");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 121 "..\..\Views\Home\Index.cshtml"
Write(Html.Action("GenerateThongTinCaNhan", "Home"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<!--End Thông tin cá nhân-->\r\n\r\n");

WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n<script");

WriteLiteral(" language=\"javascript\"");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    // Ham kiem tra ung dung
    function KiemTraUngDung(KiemTra, ungDung) {
        if (KiemTra != ""co"") {
            if (KiemTra == ""QuanTriHeThongDuocTruyCap"")
                alert(""Quản trị hệ thống mới có quyền truy cập vào ứng dụng !"");
            else
                if (KiemTra == ""QuanTriHeThongKhongTruyCap"")
                    alert(""Quản trị hệ thống không được phép truy cập vào ứng dụng !"");
                else
                    alert(""Tên đăng nhập không có quyền truy cập vào ứng dụng !"");
        }
    }
</script>

");

WriteLiteral("\r\n<script");

WriteLiteral(" language=\"javascript\"");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">

    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#file')
                    .attr('src', e.target.result)
                    .width(80)
                    .height(90);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }

</script>");

        }
    }
}
#pragma warning restore 1591
