//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_MUCDICHSUDUNGDATLS
    {
        public string MUCDICHSUDUNGDATLSID { get; set; }
        public string THUADATLSID { get; set; }
        public Nullable<decimal> SOTHUTUMDSD { get; set; }
        public string MUCDICHSUDUNGID { get; set; }
        public string MUCDICHSUDUNGQHID { get; set; }
        public Nullable<decimal> DIENTICH { get; set; }
        public Nullable<decimal> SUDUNGCHUNG { get; set; }
        public string THOIHANSUDUNG { get; set; }
        public string uId { get; set; }
        public Nullable<System.DateTime> THOIDIEMKHOITAO { get; set; }
        public string NGUOICAPNHATID { get; set; }
        public Nullable<System.DateTime> THOIDIEMCAPNHAT { get; set; }
    }
}
