//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HSV_LICHSU
    {
        public string LICHSUHOSOID { get; set; }
        public string HOSOTRUOCID { get; set; }
        public string HOSOID { get; set; }
        public string HOSOSAUID { get; set; }
        public string XAID { get; set; }
        public string TENXA { get; set; }
        public string TENHOSOHIENTAI { get; set; }
        public string TENHOSOTRUOC { get; set; }
        public string TENHOSOSAU { get; set; }
    }
}
