//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HTV_NGUOIDUNG_CHUCVU
    {
        public string NGUOIDUNGID { get; set; }
        public string CHUCVU { get; set; }
        public string TOCHUCID { get; set; }
        public string TENTOCHUC { get; set; }
    }
}
