//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT_METADATA
    {
        public string FILEIDENTIFIER { get; set; }
        public string NGONNGU { get; set; }
        public string BANGMAKYTU { get; set; }
        public string PARENTIDENTIFIER { get; set; }
        public string PHAMVIMOTA { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        public string DONVILAP { get; set; }
        public string TENCHUAN { get; set; }
        public string PHIENBAN { get; set; }
        public string XAID { get; set; }
        public string NGUOICAPNHATID { get; set; }
        public string UID { get; set; }
        public Nullable<System.DateTime> THOIDIEMKHOITAO { get; set; }
        public Nullable<System.DateTime> THOIDIEMCAPNHAT { get; set; }
    }
}
