//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QH_KHUCHUCNANGCAPTINH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QH_KHUCHUCNANGCAPTINH()
        {
            this.QH_DINHKEMKCNCAPTINH = new HashSet<QH_DINHKEMKCNCAPTINH>();
        }
    
        public string KHUCHUCNANGCAPTINHID { get; set; }
        public string MATINH { get; set; }
        public decimal NAMTHANHLAP { get; set; }
        public string TYLEBANDO { get; set; }
        public string NGUONTHANHLAP { get; set; }
        public string COQUANDUYET { get; set; }
        public string COQUANTHAMDINH { get; set; }
        public string COQUANLAP { get; set; }
        public string DONVITUVAN { get; set; }
        public string SOPHEDUYET { get; set; }
        public Nullable<System.DateTime> NGAYPHEDUYET { get; set; }
        public string TENDUAN { get; set; }
        public string FILEBANDO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QH_DINHKEMKCNCAPTINH> QH_DINHKEMKCNCAPTINH { get; set; }
    }
}
