//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QT_CONGVIECTHEOBUOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QT_CONGVIECTHEOBUOC()
        {
            this.QT_CONGVIECTHUCHIEN = new HashSet<QT_CONGVIECTHUCHIEN>();
        }
    
        public string CONGVIECTHEOBUOCID { get; set; }
        public Nullable<decimal> STT { get; set; }
        public string TENCONGVIEC { get; set; }
        public string BUOCQUYTRINHID { get; set; }
    
        public virtual QT_BUOCQUYTRINH QT_BUOCQUYTRINH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QT_CONGVIECTHUCHIEN> QT_CONGVIECTHUCHIEN { get; set; }
    }
}
