//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEWNG_NHOM
    {
        public string NGUOIID { get; set; }
        public string LOAIDOITUONGID { get; set; }
        public string NHOMNGUOIID { get; set; }
        public string THANHPHANID { get; set; }
        public Nullable<decimal> LOAIDOITUONG { get; set; }
    }
}
