//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_QT_NGUOIDUNG
    {
        public string NGUOIDUNGID { get; set; }
        public string TENDANGNHAP { get; set; }
        public string MATKHAU { get; set; }
        public string HOTENNGUOIDUNG { get; set; }
        public string GIOITINH { get; set; }
        public string SODIENTHOAI { get; set; }
        public string EMAIL { get; set; }
        public string DIACHI { get; set; }
        public string CHUCVU { get; set; }
        public string TENTOCHUC { get; set; }
        public string TOCHUCID { get; set; }
        public string KHOACHAID { get; set; }
        public string THUTUSAPXEP { get; set; }
        public string DONVIHANHCHINHID { get; set; }
    }
}
