//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_DONDK
    {
        public string DONDANGKYID { get; set; }
        public Nullable<System.DateTime> NGAYDANGKY { get; set; }
        public string HOSOTIEPNHANID { get; set; }
        public string NGUOIID_QQL { get; set; }
        public string THUADAT_QQL { get; set; }
        public string DAMUCDICHSUDUNGID_QQL { get; set; }
        public string NGUOIID_QSH { get; set; }
        public string TAISANGANLIENVOIDATID { get; set; }
        public string GIAYCHUNGNHANID_QSH { get; set; }
        public string NGUOIID_QSD { get; set; }
        public string THUADATID_QSD { get; set; }
        public string MUCDICHSUDUNGDATID_QSD { get; set; }
        public string GIAYCHUNGNHANID_QSD { get; set; }
    }
}
