#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\XLHSHoSoLuuKho\_HoSoLuuKho.cshtml"
    using AppCore.Models;
    
    #line default
    #line hidden
    using MPLIS;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/XLHSHoSoLuuKho/_HoSoLuuKho.cshtml")]
    public partial class _Views_XLHSHoSoLuuKho__HoSoLuuKho_cshtml : System.Web.Mvc.WebViewPage<HS_HOSO>
    {
        public _Views_XLHSHoSoLuuKho__HoSoLuuKho_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" id=\"divHoSoTiepNhanID\"");

WriteLiteral(" class=\"m-15\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row panel\"");

WriteLiteral(" style=\"margin-bottom: 5px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"btn btn-default btn-block tab-doc\"");

WriteLiteral(" style=\"text-align:left;\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" style=\"color: blue;font-weight: bold;\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-parent=\"#divHoSoTiepNhanID\"");

WriteLiteral(" href=\"#collapse_HoSoLuuKho_TTChung\"");

WriteLiteral(">\r\n                Thông tin lưu kho\r\n            </a>\r\n            <button");

WriteLiteral(" class=\"btn-xs btn-heading pull-right\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"LuuKho_TTchung()\"");

WriteLiteral(">Lưu</button>\r\n            <button");

WriteLiteral(" class=\"btn-xs btn-heading pull-right\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"LuuKho_Xoa()\"");

WriteLiteral(" hidden>Xóa</button>\r\n        </div>\r\n        <div");

WriteLiteral(" id=\"collapse_HoSoLuuKho_TTChung\"");

WriteLiteral(" class=\"panel-collapse collapse in\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"divHoSoTiepNhanID_TTChung\"");

WriteLiteral(">\r\n");

            
            #line 14 "..\..\Views\XLHSHoSoLuuKho\_HoSoLuuKho.cshtml"
                
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\XLHSHoSoLuuKho\_HoSoLuuKho.cshtml"
                  Html.RenderPartial("_HoSoLuuKho_TTChung", Model);
            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row panel\"");

WriteLiteral(" style=\"margin-bottom: 5px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"btn btn-default btn-block tab-doc\"");

WriteLiteral(" style=\"text-align:left;\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" style=\"color: blue;font-weight: bold;\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-parent=\"#divHoSoTiepNhanID\"");

WriteLiteral(" href=\"#collapse_HoSoLuuKho_DSFile\"");

WriteLiteral(">\r\n                Danh sách file đính kèm\r\n            </a>\r\n            <button" +
"");

WriteLiteral(" class=\"btn-xs btn-heading pull-right\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"LuuKho_DSFile()\"");

WriteLiteral(">Lưu</button>\r\n        </div>\r\n        <div");

WriteLiteral(" id=\"collapse_HoSoLuuKho_DSFile\"");

WriteLiteral(" class=\"panel-collapse collapse\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"divHoSoTiepNhanID_DSFile\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 27 "..\..\Views\XLHSHoSoLuuKho\_HoSoLuuKho.cshtml"
           Write(Html.Partial("_HoSoLuuKho_DSFile"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row panel\"");

WriteLiteral(" style=\"margin-bottom: 5px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"btn btn-default btn-block tab-doc\"");

WriteLiteral(" style=\"text-align:left;\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" style=\"color: blue;font-weight: bold;\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-parent=\"#divHoSoTiepNhanID\"");

WriteLiteral(" href=\"#collapse_HoSoLuuKho_GCN\"");

WriteLiteral(">\r\n                Thông tin phục vụ tìm kiếm theo giấy chứng nhận\r\n            <" +
"/a>\r\n            <button");

WriteLiteral(" class=\"btn-xs btn-heading pull-right\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"LuuKho_GCN()\"");

WriteLiteral(">Lưu</button>\r\n        </div>\r\n        <div");

WriteLiteral(" id=\"collapse_HoSoLuuKho_GCN\"");

WriteLiteral(" class=\"panel-collapse collapse\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"divHoSoTiepNhanID_GCN\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 40 "..\..\Views\XLHSHoSoLuuKho\_HoSoLuuKho.cshtml"
           Write(Html.Partial("_HoSoLuuKho_GCN"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row panel\"");

WriteLiteral(" style=\"margin-bottom: 5px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"btn btn-default btn-block tab-doc\"");

WriteLiteral(" style=\"text-align:left;\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" style=\"color: blue;font-weight: bold;\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-parent=\"#divHoSoTiepNhanID\"");

WriteLiteral(" href=\"#collapse_HoSoLuuKho_Thua\"");

WriteLiteral(">\r\n                Thông tin phục vụ tìm kiếm theo thửa đất\r\n            </a>\r\n  " +
"          <button");

WriteLiteral(" class=\"btn-xs btn-heading pull-right\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"LuuKho_Thua()\"");

WriteLiteral(">Lưu</button>\r\n        </div>\r\n        <div");

WriteLiteral(" id=\"collapse_HoSoLuuKho_Thua\"");

WriteLiteral(" class=\"panel-collapse collapse\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"divHoSoTiepNhanID_Thua\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 53 "..\..\Views\XLHSHoSoLuuKho\_HoSoLuuKho.cshtml"
           Write(Html.Partial("_HoSoLuuKho_Thua"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row panel\"");

WriteLiteral(" style=\"margin-bottom: 5px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"btn btn-default btn-block tab-doc\"");

WriteLiteral(" style=\"text-align:left;\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" style=\"color: blue;font-weight: bold;\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-parent=\"#divHoSoTiepNhanID\"");

WriteLiteral(" href=\"#collapse_HoSoLuuKho_Chu\"");

WriteLiteral(">\r\n                Thông tin phục vụ tìm kiếm theo chủ sử dụng\r\n            </a>\r" +
"\n            <button");

WriteLiteral(" class=\"btn-xs btn-heading pull-right\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"LuuKho_Chu()\"");

WriteLiteral(">Lưu</button>\r\n        </div>\r\n        <div");

WriteLiteral(" id=\"collapse_HoSoLuuKho_Chu\"");

WriteLiteral(" class=\"panel-collapse collapse\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"divHoSoTiepNhanID_Chu\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 66 "..\..\Views\XLHSHoSoLuuKho\_HoSoLuuKho.cshtml"
           Write(Html.Partial("_HoSoLuuKho_Chu"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n</div>\r\n<div");

WriteLiteral(" id=\"dialogformViTriLuu\"");

WriteLiteral(">\r\n</div>\r\n<script>\r\n    $(document).ready(function () {\r\n        trigger_tab_doc" +
"();\r\n    });\r\n    function LuuKho_TTchung() {\r\n        $(\'#drpxaHSLuuKho\').prop(" +
"\"disabled\", false);\r\n        $(\'#MAHOSO\').prop(\"disabled\", false);\r\n        var " +
"formdata = $(\"#div_HSLK_TTCHUNG\").serializeArray();\r\n        $.ajax({\r\n         " +
"   type: \"POST\",\r\n            url: \"/XLHSHoSoLuuKho/Save_formDonDangKy_HSLK\",\r\n " +
"           //  data: formDonDangKy_DSTAISAN.serialize(),\r\n            data: form" +
"data,\r\n            success: function (data) {\r\n                alert(data);\r\n   " +
"             $(\'#drpxaHSLuuKho\').prop(\"disabled\", true);\r\n                $(\'#MA" +
"HOSO\').prop(\"disabled\", true);\r\n            },\r\n        });\r\n    }\r\n    function" +
" LuuKho_Xoa() {\r\n      var  id = $(\'#HOSOID\').val();\r\n        $.ajax({\r\n        " +
"    type: \"POST\",\r\n            url: \"/XLHSHoSoLuuKho/Xoa_formDonDangKy_HSLK\",\r\n " +
"           //  data: formDonDangKy_DSTAISAN.serialize(),\r\n            data: { id" +
": id.trim() },\r\n            success: function (data) {\r\n                alert(da" +
"ta);\r\n            },\r\n        });\r\n    }\r\n    function LuuKho_GCN() {\r\n        $" +
".ajax({\r\n            type: \"POST\",\r\n            url: \"/XLHSHoSoLuuKho/Save_DSGCN" +
"\",\r\n            //  data: formDonDangKy_DSTAISAN.serialize(),\r\n            succe" +
"ss: function (data) {\r\n                alert(data);\r\n            },\r\n        });" +
"\r\n    }\r\n    function LuuKho_Thua() {\r\n        $.ajax({\r\n            type: \"POST" +
"\",\r\n            url: \"/XLHSHoSoLuuKho/Save_HSLK_DSTHUA\",\r\n            //  data: " +
"formDonDangKy_DSTAISAN.serialize(),\r\n            success: function (data) {\r\n   " +
"             alert(data);\r\n            },\r\n        });\r\n    }\r\n    function LuuK" +
"ho_Chu() {\r\n        $.ajax({\r\n            type: \"POST\",\r\n            url: \"/XLHS" +
"HoSoLuuKho/Save_HSLK_DSCHU\",\r\n            //  data: formDonDangKy_DSTAISAN.seria" +
"lize(),\r\n            success: function (data) {\r\n                alert(data);\r\n " +
"           },\r\n        });\r\n    }\r\n\r\n</script>");

        }
    }
}
#pragma warning restore 1591
