#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MPLIS.Modeles.QuanTriQuyTrinh;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/DiagramWorkflow/_QuyTrinh_TTQuyTrinh.cshtml")]
    public partial class _Views_DiagramWorkflow__QuyTrinh_TTQuyTrinh_cshtml : System.Web.Mvc.WebViewPage<AppCore.Models.QT_QUYTRINH>
    {
        public _Views_DiagramWorkflow__QuyTrinh_TTQuyTrinh_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"box box-default\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"box-header with-border\"");

WriteLiteral(">\r\n        <h3");

WriteLiteral(" class=\"box-title\"");

WriteLiteral(">Quy trình</h3>\r\n        <div");

WriteLiteral(" class=\"box-tools pull-right\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-sm btn-default\"");

WriteLiteral(" onclick=\"SaveQuyTrinh_TTQuyTrinh()\"");

WriteLiteral(">Lưu vào CSDL</button>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"box-body\"");

WriteLiteral(">\r\n        <form");

WriteLiteral(" id=\"form_QTQUYTRINH_ID\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 12 "..\..\Views\DiagramWorkflow\_QuyTrinh_TTQuyTrinh.cshtml"
       Write(Html.HiddenFor(model => model.QUYTRINHID));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 15 "..\..\Views\DiagramWorkflow\_QuyTrinh_TTQuyTrinh.cshtml"
               Write(Html.LabelFor(model => model.TENQUYTRINH, "Tên quy trình", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 18 "..\..\Views\DiagramWorkflow\_QuyTrinh_TTQuyTrinh.cshtml"
               Write(Html.TextBoxFor(model => model.TENQUYTRINH, "", new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 21 "..\..\Views\DiagramWorkflow\_QuyTrinh_TTQuyTrinh.cshtml"
               Write(Html.LabelFor(model => model.KYHIEU, "Ký hiệu", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 24 "..\..\Views\DiagramWorkflow\_QuyTrinh_TTQuyTrinh.cshtml"
               Write(Html.TextBoxFor(model => model.KYHIEU, "", new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 29 "..\..\Views\DiagramWorkflow\_QuyTrinh_TTQuyTrinh.cshtml"
               Write(Html.LabelFor(model => model.CAPQUYTRINH, "Cấp quy trình", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 32 "..\..\Views\DiagramWorkflow\_QuyTrinh_TTQuyTrinh.cshtml"
               Write(Html.TextBoxFor(model => model.CAPQUYTRINH, "", new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 35 "..\..\Views\DiagramWorkflow\_QuyTrinh_TTQuyTrinh.cshtml"
               Write(Html.LabelFor(model => model.THOIHANGIAIQUYETTOIDA, "Thời gian giải quyết tối đa", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 38 "..\..\Views\DiagramWorkflow\_QuyTrinh_TTQuyTrinh.cshtml"
               Write(Html.TextBoxFor(model => model.THOIHANGIAIQUYETTOIDA, "", new { @class = "form-control input-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 43 "..\..\Views\DiagramWorkflow\_QuyTrinh_TTQuyTrinh.cshtml"
               Write(Html.LabelFor(model => model.NHOMQUYTRINHID, "Nhóm quy trình", new { @class = "pull-right control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-xs-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 46 "..\..\Views\DiagramWorkflow\_QuyTrinh_TTQuyTrinh.cshtml"
               Write(Html.DropDownListFor(model => model.NHOMQUYTRINHID, new SelectList(ViewBag.dSNhomQuyTrinh, "NHOMQUYTRINHID", "TENNHOMQUYTRINH"), new { @class = "form-control input-sm", @disabled = "" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </form>\r\n    </div>\r\n</div>" +
"\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    function SaveQuyTrinh_TTQuyTrinh() {
        $('#NHOMQUYTRINHID').prop(""disabled"", false);
        $.ajax({
            type: ""POST"",
            url: ""/DiagramWorkflow/_Save_QuyTrinh_TTQuyTrinh"",
            data: $('#form_QTQUYTRINH_ID').serialize(),
            dataType: ""json"",
            success: function (result) {
                alert(""Lưu thông tin quy trình thành công!"");
            }
        })
        $('#NHOMQUYTRINHID').prop(""disabled"", true);
    }
</script>");

        }
    }
}
#pragma warning restore 1591
