#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MPLIS.Modeles.QuanTriQuyTrinh;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/DiagramWorkflow/_QuyTrinh_CauHinhXuLy_BuocQuyTrinh.cshtml")]
    public partial class _Views_DiagramWorkflow__QuyTrinh_CauHinhXuLy_BuocQuyTrinh_cshtml : System.Web.Mvc.WebViewPage<MPLIS.Libraries.Data.QuanTriQuyTrinh.Models.CauHinhXuLyVM>
    {
        public _Views_DiagramWorkflow__QuyTrinh_CauHinhXuLy_BuocQuyTrinh_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<table");

WriteLiteral(" id=\"Table_BUOCQUYTRINH_ID\"");

WriteLiteral(" class=\"table table-bordered\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n            <th></th>\r\n            <th>#</th>\r\n    " +
"        <th>Tên bước</th>\r\n            <th>Thời gian quy định</th>\r\n            " +
"<th>Mô tả</th>\r\n            <th></th>\r\n        </tr>\r\n    </thead>\r\n    <tbody>\r" +
"\n");

            
            #line 15 "..\..\Views\DiagramWorkflow\_QuyTrinh_CauHinhXuLy_BuocQuyTrinh.cshtml"
        
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\DiagramWorkflow\_QuyTrinh_CauHinhXuLy_BuocQuyTrinh.cshtml"
         if (Model.DSBuocQuyTrinh != null && Model.DSBuocQuyTrinh.Count > 0)
        {
            int sTT = 0;
            foreach (var item in Model.DSBuocQuyTrinh)
            {
                sTT++;

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 23 "..\..\Views\DiagramWorkflow\_QuyTrinh_CauHinhXuLy_BuocQuyTrinh.cshtml"
                   Write(item.BUOCQUYTRINHID);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 26 "..\..\Views\DiagramWorkflow\_QuyTrinh_CauHinhXuLy_BuocQuyTrinh.cshtml"
                   Write(sTT);

            
            #line default
            #line hidden
WriteLiteral(".\r\n                    </td>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 29 "..\..\Views\DiagramWorkflow\_QuyTrinh_CauHinhXuLy_BuocQuyTrinh.cshtml"
                   Write(item.TENBUOC);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 32 "..\..\Views\DiagramWorkflow\_QuyTrinh_CauHinhXuLy_BuocQuyTrinh.cshtml"
                   Write(item.THOIGIANQUYDINH);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 35 "..\..\Views\DiagramWorkflow\_QuyTrinh_CauHinhXuLy_BuocQuyTrinh.cshtml"
                   Write(item.MOTA);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td></td>\r\n                </tr>" +
"\r\n");

            
            #line 39 "..\..\Views\DiagramWorkflow\_QuyTrinh_CauHinhXuLy_BuocQuyTrinh.cshtml"
            }
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    var curBUOCQUYTRINHID = \"\";\r\n    $(document).ready(function () {\r\n        " +
"var columns = [\r\n            { \"data\": \"BUOCQUYTRINHID\" },\r\n            { \"data\"" +
": \"STT\" },\r\n            { \"data\": \"TENBUOC\" },\r\n            { \"data\": \"THOIGIANQ" +
"UYDINH\" },\r\n            { \"data\": \"MOTA\" },\r\n            { \"data\": null }\r\n     " +
"   ]\r\n        var columnDefs = [\r\n            {\r\n                \"targets\": 0,\r\n" +
"                \"visible\": false\r\n            },\r\n            {\r\n               " +
" \"targets\": 1,\r\n                \"className\": \"text-right\"\r\n            },\r\n     " +
"       {\r\n                \"targets\": -1,\r\n                \"render\": function () " +
"{\r\n                    return \"<button type=\'button\' class=\'btn btn-xs btn-headi" +
"ng btnEdit\'>Chỉnh sửa</button>\";\r\n                },\r\n                \"className" +
"\": \"text-center\"\r\n            },\r\n            {\r\n                \"targets\": 3,\r\n" +
"                \"className\": \"text-center\"\r\n            }\r\n        ]\r\n        va" +
"r options = {\r\n            \"pageLength\": 5,\r\n            \"lengthChange\": false,\r" +
"\n            \"ordering\": false,\r\n            \"info\": false,\r\n            \"search" +
"ing\": false,\r\n            \"autoWidth\": false,\r\n            \"language\": {\r\n      " +
"          \"url\": \"https://cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Vietnames" +
"e.json\"\r\n            },\r\n            \"columns\": columns,\r\n            \"columnDef" +
"s\": columnDefs,\r\n            \"dom\": \"<\'row p-0\'<\'col-sm-12 p-0\'tr>><\'row p-0\'<\'c" +
"ol-sm-6 p-0\'><\'col-sm-6 p-0\'p>>\"\r\n        }\r\n\r\n        var Table_BUOCQUYTRINH_ID" +
" = $(\'#Table_BUOCQUYTRINH_ID\').DataTable(options);\r\n        \r\n    })\r\n</script>\r" +
"\n");

        }
    }
}
#pragma warning restore 1591
